# 独立确认结果核查

读取已保存的 Qwen-27B、Gemma 与读出重复性结果，检查随机对照失败、物理条件分组和历史读出差异。

CPU 运行；保留原确认状态与 2% 容差，结果导出为 ZIP。

[实验设置与运行说明](../../../docs/experiment_notes/04_section45_guided_repair/313e5a041e25d1f0.md)

In [ ]:
# Notebook utilities: support/visualtorque_checks.py
import base64 as _vt_base64, gzip as _vt_gzip, sys as _vt_sys, types as _vt_types
_vt_source = _vt_gzip.decompress(_vt_base64.b64decode("H4sIAAAAAAACCo1Y647bthL+76dgtziwtLGVTZAGqFs3J8BJkABJESCLoqjXFWiJsnmWElWS2qx7Afo0fbA+SWd4kSnJ23Z/JBLnPvPNcOSLi4vXXDBSHFhxqwltStJIw3ZS3pKS61bQI+kMF9xwpjPyrSS1LJkgUhF23zLFa9YYUrKWNSVrCmS6uLiY8bqVypCqawojpdDh4ED1QfBdeFUsPOmjnlVK1uRgapG1VGmmiKe9uX7/7oM9cSwtNagkkD/A62w2K1lFKgglRxsJ8qSrGYG/ku+ZNmQdjGf6QJ9+8TxJLfUTNwerwolkEiJJ5mo3TwnVINKUgjk9+FdB3MWha24Jbwg3TCWC1ruSrjxnphgtkydXT5+RS4L/pQuym8/Tk4aTR1nXltSwxOpzzihmOtUE+oHduydw1cXnPM8xzDhCLzZ35NWcPBpnYiqf7455Q2uW2JepstjUiQX0AAFyGZFnljw9diZ3R8M0UhMIlj7s8Kg4lvlMBhqpair4z9ZgckdFx0Z+G+WPoRa1vGOtYhW/T3pbqCl/8/LjG3BXsayQdYsxqnny4uvPNi+XP9Dlz1fLL/NtmrxYbeCJLquXy9fbX54/++3X+P3Z1W/AMhQB7fn1q++v8/dv37/6CBaSuWH35jH0EW/mC+LeEOP9S03VbSk/NfMQInpEC5MjNcF/FjY5TK+/lU2IFprs4wHQz5rQpqz0bAsiW8NlQ4U4klvGWt7sCYVY75jSfAfNLqC7u9Y2qoUjGFUMdBQsqakpDhFcbSohDnue7ZXsWt84+KfRBaBars3qydUWKjn/8/c/sKLucPl8te35eeV9JFzjnCEY0bA3eOW1QoN5XhxK7nFjSVvymTc5FI1QYKkD4lDBesTRgx6oMZosUDLd7RKfoAXBimCpCkG1Jvl33Ob0Got1GlRh9EBm85w33OR5opmonHgoaJRn3cEwTdKs5y5kA/UyeXGgChCs16+p0CxKPWjLnDL7GGpvX0CogbaBMGNzC7LZDuVlVWlmkG9zdZ6UgTyM9qTO8N/UDsAaawOtU/GmtDNwfoPYtokZOSiQTgUYwErP+qS4aZlrQ5UxdB9yQ/cLQo1RcWYAEHCOJqGHC8Vbg62jzVGw8VwdmQSxiUWIYmBvami9Huj5Wwtng8LR5Q1EIy9g+0HVDnH9kSthCUYG8wA1DiqextqDEPQHMg4NCN4AfAspurohPsg9M63UUUfbILEqgcPjYIPSZEmeYIc7HdPEeNhltMV1IEmsooXX94gIuFltRhbB0XQ883Ay/t3Me8foHbMQ4bvOIKTBr1uEvUUGPiAw3MzgNd0zmwhAjwH1/cTz+8V62L6D1oz4soqxMnF9H50WQmrmU4dt4aOFyBd+bNo2wakL4kHIpSgCBer1jbpZWR3bMDzhf3sMKv0Q9WMJT0eZC9fIg9n7nLyDVAFQteENxQtCg7oa7iXSaQo5WIC/hehKvC5sVomRVs8S94SSgGe8AlM6C1mwkwMGAdw/3OANerO9STY/ptvLm/TXgzGtfrF6/Hjz443++pvtozTMiMEKMM/+L3mD6TGIYE7+Q54SBqNuiPvW5nYM+egPK8AXxOlpoApdDT1mmJXUE6DZ/LpFYUFq2GLXw4t6mj+7y0LWoo5EtKLTKI9zI7rdhyGE4kyZ+9t/GvPMNzUgtAFcNEXvr+DaRAj6nDS7CvciQ+ASqTmUhZK6E7i2Q9PCRoQlhWLu8EUqrCV2CFRU0WPW68FC2IkTiuL2qOiS1KAU6CEViZOY1sUX1wk4eKArOsF1BNCs19cKNGN0XilMLG/e5uF0O3tVvUmfAm/xfH4g4jTWM+oUKICfo9Mq9zGWvHDT9tTgtnKArWjDG8z2QHc6xtMdzzbIso0Q5GAYEx0ahykdpPO0evzPLX4fDXx01M5cfsd1RwUU+acOr1ekgDnM9uyhjcRxxbsIzvKTsHs4iX9ScH1F28wDkpnjm2yz6QQmeC/4rWpgw0HGGbLP6fBDzKIb8m1pZ+5p5wBSI82V6OCjCOmRtrD+xe47xjROG9yWePX0mcO5ONXiuZJYm+f1SMxhoYNiHjxRJ5dU7eHuury8/YRPYeJAjCjmdx9Tys7vPiVTKl5++lr1to86mIyXD8cW7d7hg/8k6N2dn0MSGHdb6DjZI6OLETa91n4I4/chbEC5/3JJYP4xBcBn5iDL3GmAPHT424K3JRXfw7UlohjPSdlODoOzl4GAbbCQz17Y0yaRep/OhOoXNPv+3/6XDUAZbXWvL+3h0nY7mNOHB2rrXcSTYTLxBL8bB9MKD2FDh8XJats8WW1PhYU+qfp0IVacoaFadxbmmnflDMcmKIqnlPVhTJ+0cUjBJGKXMp+P7Gy6w4yK4XSuvl5JAJId/EL0QIKRKcRoZXxtsTb9VUs24viVuyDAWfzFwm2NxYGLctkqWTAYskJC1sDIEW4gIfoF0n6lgq0ArWidU8dh5u1PVm8/HCGKJvxkBSjMeWuPTmW8L1hryFvL8Uopqc59HzhURh/g6MQ6Vpik/+DhRNFkHDkN4y616jL/lkMloHd8PXAq4V05/xeSBygCsNvhnLu1xX4yoY7wChid92EMxhNqemA65aj5TN8667CHN7C6KraH5Qm/WVvFctU1eQFUkBonIR3JP2gxhq5PrX3/C0ov0eJaFQAA"))
_vt_checks = _vt_types.ModuleType("visualtorque_checks")
exec(compile(_vt_source, "<visualtorque_checks>", "exec"), _vt_checks.__dict__)
_vt_sys.modules["visualtorque_checks"] = _vt_checks
_vt_checks.install_display()
del _vt_source

In [1]:
# Run once. Every later code cell reports both cell and inner-loop progress.
import re
import threading
import time
from IPython.core.magic import register_cell_magic
from tqdm.auto import tqdm

_SETUP_PROGRESS = tqdm(total=1, desc='Initialize progress display', unit='cell')
_ACTIVE_CELL_PROGRESS = None

def cell_stage(message):
    if _ACTIVE_CELL_PROGRESS is not None:
        _ACTIVE_CELL_PROGRESS['stage'] = str(message)
        elapsed = time.monotonic() - _ACTIVE_CELL_PROGRESS['started']
        _ACTIVE_CELL_PROGRESS['bar'].set_postfix_str(
            f"{message} | elapsed {elapsed:.0f}s", refresh=True
        )

@register_cell_magic
def cell_progress(line, cell):
    global _ACTIVE_CELL_PROGRESS
    specification = line.strip() or 'Cell progress'
    match = re.fullmatch(r'(\d+)/(\d+)\s+(.+)', specification)
    if match:
        current, total, label = int(match.group(1)), int(match.group(2)), match.group(3)
        initial = current - 1
    else:
        current, total, label, initial = 1, 1, specification, 0
    started = time.monotonic()
    bar = tqdm(
        total=total, initial=initial, desc=label, unit='cell',
        dynamic_ncols=True, leave=True,
    )
    state = {'bar': bar, 'started': started, 'stage': 'starting'}
    _ACTIVE_CELL_PROGRESS = state
    stopped = threading.Event()

    def heartbeat():
        while not stopped.wait(1.0):
            elapsed = time.monotonic() - started
            bar.set_postfix_str(
                f"{state['stage']} | elapsed {elapsed:.0f}s", refresh=True
            )

    worker = threading.Thread(target=heartbeat, daemon=True)
    worker.start()
    succeeded = False
    try:
        cell_stage('running')
        result = get_ipython().run_cell(cell)
        result.raise_error()
        succeeded = True
        return result.result
    finally:
        stopped.set()
        worker.join(timeout=2.0)
        elapsed = time.monotonic() - started
        if succeeded:
            bar.n = current
            bar.set_postfix_str(f"complete | elapsed {elapsed:.0f}s", refresh=True)
        else:
            bar.set_postfix_str(f"failed | elapsed {elapsed:.0f}s", refresh=True)
        bar.close()
        _ACTIVE_CELL_PROGRESS = None

_SETUP_PROGRESS.update(1)
_SETUP_PROGRESS.close()
print('Cell progress helper ready.')

IMPLEMENTATION_SHA256 = '160372af558929c42134517d3ffc09527278d018135dd39a46f32eb6987dde7d'
IMPLEMENTATION_SHA256 = '17ffb36148a134134b1fd15d3c2d5e5435e240c80f3c6466243d49cb3c71051e'

Initialize progress display:   0%|          | 0/1 [00:00<?, ?cell/s]

Cell progress helper ready.

In [2]:
%%cell_progress 1/10 Mount Drive
cell_stage('Mounting Google Drive')
from google.colab import drive
drive.mount('/content/drive')

cell_stage('Locating VisualTorque project')
from pathlib import Path
PROJECT_CANDIDATES = (
    Path('/content/drive/MyDrive/VisualTorque'),
    Path('/content/drive/MyDrive/VisualTorque/VisualTorque'),
)
PROJECT_ROOT = next(
    (
        path for path in PROJECT_CANDIDATES
        if (path / 'toolkit' / 'pyproject.toml').is_file()
    ),
    None,
)
assert PROJECT_ROOT is not None, (
    'Could not find VisualTorque/toolkit/pyproject.toml on Drive.'
)
TOOLKIT_ROOT = PROJECT_ROOT / 'toolkit'
print('Project:', PROJECT_ROOT)

Mount Drive:   0%|          | 0/10 [00:00<?, ?cell/s]

Mounted at /content/drive
Project: /content/drive/MyDrive/VisualTorque

In [3]:
%%cell_progress 2/10 Load CPU analysis libraries
import sys,subprocess
subprocess.check_call([sys.executable,'-m','pip','install','-q','numpy','pandas','tqdm'])
from IPython.display import display

Load CPU analysis libraries:  10%|#         | 1/10 [00:00<?, ?cell/s]

In [4]:
%%cell_progress 3/10 Load shared validation utilities
"""Pure CPU utilities embedded in the follow-up notebooks; no model execution."""
import hashlib
import json
from pathlib import Path
from collections import defaultdict, Counter
from itertools import combinations, product
import numpy as np
import pandas as pd


def plain(value):
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, np.generic):
        return value.item()
    raise TypeError(type(value).__name__)


def digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, default=plain, allow_nan=False).encode()).hexdigest()


from visualtorque_checks import file_hash


def read_json(path):
    return json.loads(Path(path).read_text(encoding='utf-8'))


def read_jsonl(path):
    return [json.loads(s) for s in Path(path).read_text(encoding='utf-8').splitlines() if s.strip()]


def save_json(path, value):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_suffix(path.suffix + '.tmp')
    temp.write_text(json.dumps(value, ensure_ascii=False, indent=2, default=plain, allow_nan=False) + '\n', encoding='utf-8')
    temp.replace(path)


def freeze(path, identity):
    identity = json.loads(json.dumps(identity, default=plain, sort_keys=True, allow_nan=False))
    if Path(path).is_file():
        assert read_json(path) == identity, f'Configuration changed; preserve the old run and use a new RUN_ID: {path}'
    else:
        save_json(path, identity)
    return digest(identity)


def cached_json(directory, key, identity, compute):
    path = Path(directory) / (digest(str(key))[:24] + '.json')
    expected = digest(identity)
    if path.is_file():
        old = read_json(path)
        assert old['key'] == str(key) and old['identity'] == expected, f'Incompatible cache: {path}'
        return old['result']
    value = compute()
    save_json(path, dict(key=str(key), identity=expected, result=value))
    return value


def bootstrap(values, key='', replicates=10000):
    x = np.asarray(values, dtype=float)
    assert x.ndim == 1 and len(x) and np.isfinite(x).all()
    rng = np.random.default_rng(int(digest(str(key))[:16], 16))
    draws = np.concatenate([rng.choice(x, (min(250, replicates-i), len(x)), replace=True).mean(1)
                            for i in range(0, replicates, 250)])
    return dict(n=len(x), mean=float(x.mean()), lower=float(np.quantile(draws, .025)),
                upper=float(np.quantile(draws, .975)),
                p_value=float((1 + (draws <= 0).sum()) / (replicates + 1)))


def bh(values):
    p = np.asarray(values, dtype=float)
    assert np.isfinite(p).all() and ((p >= 0) & (p <= 1)).all()
    order = np.argsort(p)
    q = np.empty_like(p)
    previous = 1.
    for rank in range(len(p)-1, -1, -1):
        i = order[rank]
        previous = min(previous, p[i]*len(p)/(rank+1))
        q[i] = previous
    return q


def paired(left, right, id_col, value):
    assert left[id_col].is_unique and right[id_col].is_unique
    assert set(left[id_col]) == set(right[id_col]), 'Different paired support'
    out = left[[id_col, value]].merge(right[[id_col, value]], on=id_col, validate='one_to_one', suffixes=('_l', '_r'))
    return out[value+'_l'].to_numpy(float) - out[value+'_r'].to_numpy(float)


def semantic_scores(record):
    if 'semantic_logprobs' in record:
        return {str(k): float(v) for k, v in record['semantic_logprobs'].items()}
    values = record['candidate_logprobs']
    if isinstance(values, dict):
        return {str(record['label_to_semantic'][k]): float(v) for k, v in values.items()}
    return dict(zip(map(str, record['candidate_semantics']), map(float, values)))


def correct_margin(record):
    values = semantic_scores(record)
    gold = str(record['gold_semantic'])
    assert gold in values and len(values) >= 2
    return values[gold] - max(v for k, v in values.items() if k != gold)


def random_unit(shape, key):
    r = np.random.default_rng(int(digest(key)[:16], 16)).normal(size=shape)
    return r / np.linalg.norm(r)


def coordinate_clamp(pre, untreated, axis, cast):
    h, base, u = [np.asarray(x, dtype=np.float64) for x in (pre, untreated, axis)]
    u = u / np.linalg.norm(u)
    a = float(np.sum((h-base)*u))
    return np.asarray(cast(h-a*u), dtype=np.float64), a


def native_norm_edit(pre, direction, norm, cast, tolerance=.02, steps=48):
    h = np.asarray(pre, dtype=np.float64)
    r = np.asarray(direction, dtype=np.float64)
    assert np.isfinite(h).all() and np.isfinite(r).all() and norm >= 0 and np.linalg.norm(r) > 0
    r /= np.linalg.norm(r)
    if norm == 0:
        return h.copy(), dict(actual_norm=0., target_norm=0., relative_error=0., matched=True)
    lo, hi = 0., max(float(norm), 1e-12)
    for _ in range(32):
        if np.linalg.norm(np.asarray(cast(h+hi*r))-h) >= norm:
            break
        hi *= 2
    best, error = h.copy(), 1.
    for _ in range(steps):
        mid = (lo+hi)/2
        candidate = np.asarray(cast(h+mid*r), dtype=np.float64)
        actual = float(np.linalg.norm(candidate-h))
        current = abs(actual-norm)/norm
        if current < error:
            best, error = candidate.copy(), current
        if error <= tolerance:
            break
        if actual < norm:
            lo = mid
        else:
            hi = mid
    return best, dict(actual_norm=float(np.linalg.norm(best-h)), target_norm=float(norm),
                      relative_error=float(error), matched=bool(error <= tolerance))


def equal_removal(pre, untreated, axis, random_direction, cast, tolerance=.02):
    target, coefficient = coordinate_clamp(pre, untreated, axis, cast)
    target_norm = float(np.linalg.norm(target-np.asarray(pre)))
    sign = 1. if coefficient >= 0 else -1.
    post, audit = native_norm_edit(pre, -sign*np.asarray(random_direction), target_norm, cast, tolerance)
    audit.update(reference_coefficient=coefficient, reference_actual_norm=target_norm)
    return post, audit


def geometry_signature(stacks):
    a = tuple(sorted((str(s['side']), int(s['distance']), int(s['units'])) for s in stacks))
    b = tuple(sorted(('right' if side == 'left' else 'left', d, u) for side, d, u in a))
    return min(a, b)  # mirrors belong to the same physical family


def geometries_in(value):
    found = set()
    if isinstance(value, dict):
        stacks = value.get('stacks')
        if isinstance(stacks, list) and stacks and all(isinstance(s, dict) and {'side','distance','units'} <= set(s) for s in stacks):
            found.add(geometry_signature(stacks))
        # Some prior matched cohorts store geometry instead of stack records.
        geom = value.get('pair_geometry')
        if isinstance(geom, (list, tuple)) and len(geom) == 4 and all(isinstance(x, (int,float)) for x in geom):
            u1,d1,u2,d2 = map(int, geom)
            found.add(geometry_signature([dict(side='left',distance=d1,units=u1),dict(side='right',distance=d2,units=u2)]))
        if isinstance(geom, (list, tuple)) and len(geom)==2 and all(isinstance(x,(list,tuple)) and len(x)==2 for x in geom):
            (u1,d1),(u2,d2)=geom
            found.add(geometry_signature([dict(side='left',distance=int(d1),units=int(u1)),dict(side='right',distance=int(d2),units=int(u2))]))
        for child in value.values():
            found.update(geometries_in(child))
    elif isinstance(value, list):
        for child in value:
            found.update(geometries_in(child))
    return found


def physics(stacks):
    units = {s:sum(int(x['units']) for x in stacks if x['side']==s) for s in ('left','right')}
    dist = {s:sum(int(x['distance']) for x in stacks if x['side']==s) for s in ('left','right')}
    torque = {s:sum(int(x['units'])*int(x['distance']) for x in stacks if x['side']==s) for s in ('left','right')}
    out = lambda x:'left' if x>0 else 'right' if x<0 else 'balanced'
    net=torque['left']-torque['right']; w=units['left']-units['right']; d=dist['left']-dist['right']
    return dict(net_torque=net,outcome=out(net),weight_score=w,distance_score=d,
                normalized_margin=abs(net)/max(1,sum(torque.values())),
                left_units=units['left'],right_units=units['right'],left_torque=torque['left'],right_torque=torque['right'],
                strategy_predictions=dict(exact_torque=out(net),weight_only=out(w),distance_only=out(d)))


def exclusion_snapshot(project, followup_root, dataset_dir=None):
    lock=Path(followup_root)/'prior_geometry_snapshot.json'
    if lock.is_file():
        old=read_json(lock)
        for path, sha in old['files'].items():
            assert file_hash(Path(path))==sha, f'Prior input changed: {path}'
        return {tuple(tuple(x) for x in sig) for sig in old['signatures']}, old
    paths={Path(dataset_dir or project/'data/dataset_v1')/'scenes.jsonl'}
    for pattern in ('*manifest*.jsonl','*support*.jsonl','*geometries*.jsonl'):
        paths.update(p for p in (project/'results').rglob(pattern) if Path(followup_root) not in p.parents)
    excluded=set(); hashes={}
    for path in sorted(paths):
        assert path.is_file(), f'Missing required geometry input: {path}'
        excluded.update(geometries_in(read_jsonl(path)))
        hashes[str(path.resolve())]=file_hash(path)
    assert excluded, 'No prior physical geometry was indexed'
    old=dict(files=hashes,signatures=sorted(excluded),mirror_canonical=True)
    save_json(lock,old)
    return excluded,old


def inverse_families(n, seed, excluded):
    assert n%4==0
    pool=defaultdict(list)
    for dl in combinations(range(1,7),2):
        for dr in combinations(range(1,7),2):
            for units in product(range(1,6), repeat=4):
                stacks=[dict(side=side,distance=d,units=u) for side,d,u in zip(('left','left','right','right'),dl+dr,units)]
                f=physics(stacks)
                pool[dl+dr].append((stacks,f))
    candidates=[]
    for distances,rows in pool.items():
        by_net=defaultdict(list)
        for stacks,f in rows:
            if f['outcome']==f['strategy_predictions']['weight_only'] and f['outcome']!='balanced':
                by_net[f['net_torque']].append((stacks,f))
        for stacks,f in rows:
            margin=f['normalized_margin']; difficulty='hard' if .08<=margin<.22 else 'moderate' if .22<=margin<.45 else None
            if (difficulty and f['outcome']!='balanced' and f['strategy_predictions']['weight_only'] not in ('balanced',f['outcome'])
                    and f['strategy_predictions']['distance_only']==f['outcome'] and abs(f['distance_score'])>=2):
                sources=by_net.get(f['net_torque'],[])
                if sources:candidates.append((digest([seed,stacks]),difficulty,stacks,f,sources))
    candidates.sort(key=lambda r:r[0]); used=set(excluded); counts=Counter(); result=[]
    for _,difficulty,stacks,f,sources in candidates:
        stratum=(difficulty,f['outcome'])
        if counts[stratum]>=n//4 or geometry_signature(stacks) in used:continue
        valid=[(s,g) for s,g in sources if geometry_signature(s) not in used|{geometry_signature(stacks)}]
        if not valid:continue
        valid.sort(key=lambda x:(sum(abs(a['units']-b['units']) for a,b in zip(stacks,x[0])),digest([seed,x[0]])))
        src,sf=valid[0];fid='fixed_'+digest([seed,stacks,src])[:20]
        roles={name:dict(scene_id=fid+'__'+name,image_filename=fid+'__'+name+'.png',stacks=s,features=g)
               for name,s,g in [('base',stacks,f),('aligned_source',src,sf)]}
        result.append(dict(family_id=fid,remapping_split='new_fixed_confirmation',roles=roles,margin_bin=difficulty))
        used.update([geometry_signature(stacks),geometry_signature(src)]);counts[stratum]+=1
        if len(result)==n:break
    assert len(result)==n and set(counts.values())=={n//4}, (len(result),counts)
    return sorted(result,key=lambda r:r['family_id'])


def repair_families(n, seed, excluded):
    assert n%4==0
    candidates=defaultdict(list)
    for ul,dl,ur,dr in product(range(1,9),range(1,7),range(1,9),range(1,7)):
        s=[dict(side='left',units=ul,distance=dl),dict(side='right',units=ur,distance=dr)]
        f=physics(s)
        if f['net_torque']==0:continue
        if ul==ur and dl!=dr:kind='equal_weight_distance'
        elif f['strategy_predictions']['weight_only'] not in ('balanced',f['outcome']):kind='weight_distance_conflict'
        elif f['strategy_predictions']['weight_only']==f['outcome'] and f['strategy_predictions']['distance_only']==f['outcome']:kind='aligned_cues'
        else:continue
        candidates[kind].append(s)
    for units in product(range(1,6),repeat=4):
        for distances in [((1,3),(2,5)),((2,5),(1,4)),((1,6),(3,5)),((2,4),(3,6))]:
            s=[dict(side=side,distance=d,units=u) for side,d,u in zip(('left','left','right','right'),distances[0]+distances[1],units)]
            if physics(s)['net_torque']!=0:candidates['multi_stack_sum'].append(s)
    used=set(excluded); result=[]
    for kind in ('equal_weight_distance','weight_distance_conflict','multi_stack_sum','aligned_cues'):
        rows=sorted(candidates[kind],key=lambda s:digest([seed,kind,s])); count=0
        for stacks in rows:
            sig=geometry_signature(stacks)
            if sig in used:continue
            fid='repair_'+digest([seed,kind,sig])[:20];scenes=[]
            for mirror in (False,True):
                current=[dict(s,side=('right' if s['side']=='left' else 'left')) if mirror else dict(s) for s in stacks]
                for style in ('standard','alternate'):
                    sid=f'{fid}__m{int(mirror)}__{style}'
                    scenes.append(dict(scene_id=sid,image_filename=sid+'.png',stacks=current,features=physics(current),style=style,mirror=mirror))
            result.append(dict(family_id=fid,stratum=kind,scenes=scenes));used.add(sig);count+=1
            if count==n//4:break
        assert count==n//4,(kind,count,'Insufficient unused geometries; do not silently change task ranges')
    return sorted(result,key=lambda r:r['family_id'])


def intervention_conditions(model, sign, upstream, semantic, code, untreated, key, seeds=(0, 1, 2, 3)):
    """Condition topology is fixed before observing the recipient's answer."""
    if model == 'gemma12b':
        add = {31: dict(action='add', payload=sign * upstream)}
        return [('zero', -1, {}), ('targeted', -1, add)] + [
            ('random', s, {31: dict(action='matched_add', reference=sign * upstream, key=key + ['random', s])})
            for s in seeds]
    assert model == 'qwen27b' and set(untreated) >= {49, 55}
    u = {48: dict(action='add', payload=sign * upstream)}
    a = {49: dict(action='add', payload=sign * semantic)}
    b = {55: dict(action='add', payload=code)}
    blocks = {49: dict(action='clamp', untreated=untreated[49], axis=sign * semantic),
              55: dict(action='clamp', untreated=untreated[55], axis=code)}
    rows = [('zero', -1, {}), ('u', -1, u), ('a', -1, a), ('b', -1, b),
            ('bypass', -1, {**u, 49: blocks[49], **b})]
    for name, layer, payload in [('u', 48, sign * upstream), ('a', 49, sign * semantic)]:
        for s in seeds:
            rows.append((name + '_random', s, {layer: dict(action='matched_add', reference=payload, key=key + [name, s])}))
    for layer in (49, 55):
        rows += [(f'self_{layer}', -1, {layer: blocks[layer]}),
                 (f'self_random_{layer}', 0, {layer: dict(blocks[layer], action='random_coordinate', key=key + ['self', layer, 0])})]
    for name, start, layer in [('ua', u, 49), ('ub', u, 55), ('ab', a, 55)]:
        rows.append((name + '_block', -1, {**start, layer: blocks[layer]}))
        rows.append((name + '_coordinate', 0, {**start, layer: dict(blocks[layer], action='random_coordinate', key=key + [name, 'coordinate', 0])}))
        for s in seeds:
            rows.append((name + '_equal', s, {**start, layer: dict(blocks[layer], action='equal_remove', key=key + [name, 'equal', s])}))
    assert len(rows) == 35 and len({(n, s) for n, s, _ in rows}) == len(rows)
    return rows

def reference_for_condition(model, condition):
    if model == 'gemma12b':
        return ('targeted', 31) if condition == 'random' else None
    return {'u_random': ('u', 48), 'a_random': ('a', 49),
            'ua_equal': ('ua_block', 49), 'ub_equal': ('ub_block', 55),
            'ab_equal': ('ab_block', 55)}.get(condition)

def primary_contrasts(model):
    if model == 'gemma12b':
        return [('target_vs_zero', 'targeted', 'zero'), ('target_vs_random', 'targeted', 'random')]
    return [('u_vs_zero', 'u', 'zero'), ('u_vs_random', 'u', 'u_random'),
            ('a_vs_zero', 'a', 'zero'), ('a_vs_random', 'a', 'a_random'),
            ('ua_specific_loss', 'ua_equal', 'ua_block'),
            ('ub_specific_loss', 'ub_equal', 'ub_block'), ('ab_specific_loss', 'ab_equal', 'ab_block')]

def paired_summary(values, key, two_sided=False, replicates=10000):
    """Family percentile CI; paired sign-flip test (symmetric-null assumption)."""
    x = np.asarray(values, float)
    result = bootstrap(x, key, replicates)
    rng = np.random.default_rng(int(digest(['sign_flip', key])[:16], 16))
    observed = abs(x.mean()) if two_sided else x.mean()
    exceed = 0
    for offset in range(0, replicates, 250):
        signs = rng.choice([-1., 1.], size=(min(250, replicates - offset), len(x)))
        null = (signs * x).mean(1)
        if two_sided:
            null = abs(null)
        exceed += int((null >= observed - 1e-15).sum())
    result['p_value'] = (exceed + 1) / (replicates + 1)
    return result

def test_family_contrasts(frame, model, scope='all_attempted'):
    metrics = ['accuracy_change', 'margin_change']
    # Seeds first, then the fixed scene/mapping variants, then independent families.
    units = frame.groupby(['family_id', 'scene_id', 'variant', 'condition'])[metrics].mean().reset_index()
    means = units.groupby(['family_id', 'condition'])[metrics].mean().reset_index()
    tests = []
    for name, a, b in primary_contrasts(model):
        left, right = means[means.condition.eq(a)], means[means.condition.eq(b)]
        for metric in metrics:
            values = paired(left, right, 'family_id', metric)
            tests.append(dict(contrast=name, metric=metric, scope=scope,
                              **paired_summary(values, [model, scope, name, metric])))
    tests = pd.DataFrame(tests)
    tests['q_value'] = bh(tests.p_value)
    assert len(tests) == (4 if model == 'gemma12b' else 14)
    return tests, means

def confirmation_decisions(tests, frame, model):
    def passes(name, metric):
        row = tests[tests.contrast.eq(name) & tests.metric.eq(metric)].iloc[0]
        return bool(row.lower > 0 and row.q_value < .05)
    def valid(conditions):
        sub = frame[frame.condition.isin(conditions)]
        return bool(len(sub) and sub.valid.all())
    if model == 'gemma12b':
        result = {metric: bool(passes('target_vs_zero', metric) and passes('target_vs_random', metric)
                              and valid(['targeted', 'random'])) for metric in ('accuracy_change', 'margin_change')}
        return dict(accuracy_repair_confirmed=result['accuracy_change'], score_effect_confirmed=result['margin_change'],
                    next_step='eligible_for_separate_L31_to_L47_experiment' if result['accuracy_change'] else 'stop_this_candidate_no_rescan')
    result = {}
    for metric in ('accuracy_change', 'margin_change'):
        repair = {site: bool(passes(site + '_vs_zero', metric) and passes(site + '_vs_random', metric)
                            and valid([site, site + '_random'])) for site in ('u', 'a')}
        paths = {}
        for name, start, layer in [('ua', 'u', 49), ('ub', 'u', 55), ('ab', 'a', 55)]:
            paths[name] = bool(repair[start] and passes(name + '_specific_loss', metric)
                               and valid([name + '_equal', name + '_block', f'self_{layer}', f'self_random_{layer}']))
        result[metric] = dict(repair_confirmed=repair, selective_dependence_confirmed=paths)
    return result

def validate_trial_grid(frame, families, model):
    expected = [('zero', -1), ('targeted', -1)] + [('random', s) for s in range(4)] if model == 'gemma12b' else None
    if expected is None:
        mock = intervention_conditions('qwen27b', 1, np.ones(2), np.ones(2), np.ones(2), {49: np.zeros(2), 55: np.zeros(2)}, [])
        expected = [(n, s) for n, s, _ in mock]
    assert not frame.duplicated(['family_id', 'scene_id', 'variant', 'condition', 'random_seed']).any()
    assert set(frame.family_id) == {f['family_id'] for f in families}
    for family in families:
        sub = frame[frame.family_id.eq(family['family_id'])]
        assert set(sub.scene_id) == {s['scene_id'] for s in family['scenes']}
        assert len(sub) == 4 * 2 * len(expected)
        for _, unit in sub.groupby(['scene_id', 'variant']):
            assert set(zip(unit.condition, unit.random_seed)) == set(expected)
        assert set(sub.variant) == {'forward', 'reverse'}

"""CPU-only diagnosis of saved independent-confirmation results.

Embedded after the frozen analysis helpers. Never changes input records or gates.
"""


def bool_value(value):
    if isinstance(value, (bool, np.bool_)):
        return bool(value)
    if isinstance(value, str) and value.lower() in ('true', 'false'):
        return value.lower() == 'true'
    if isinstance(value, (int, float, np.number)) and value in (0, 1):
        return bool(value)
    raise ValueError(f'Missing or invalid boolean: {value!r}')


def tracked_json(path, inputs):
    inputs[str(path)] = file_hash(path)
    return read_json(path)


def tracked_csv(path, inputs):
    inputs[str(path)] = file_hash(path)
    try:
        return pd.read_csv(path)
    except pd.errors.EmptyDataError:
        return pd.DataFrame()


def load_science_result(root, model, inputs):
    root = Path(root)
    paths = {'completion': root/'analysis/RUN_COMPLETE.json', 'protocol': root/'protocol.json',
             'capture': root/'capture_identity.json', 'support': root/'cohort/support.json',
             'records': root/'analysis/intervention_records.json', 'primary': root/'analysis/primary_tests.csv',
             'vectors': root/'frozen_directions.npz', 'reference': root/'reference.json',
             'images': root/'cohort/images.json'}
    missing = [str(p) for p in paths.values() if not p.is_file()]
    if missing:
        return dict(model=model, status='missing_inputs', issues=missing)
    result = tracked_json(paths['completion'], inputs)
    protocol = tracked_json(paths['protocol'], inputs)
    capture = tracked_json(paths['capture'], inputs)
    assert protocol['schema'] == ('qwen_three_path-1.0' if model == 'qwen27b' else 'gemma_l31_candidate-1.0')
    assert protocol['layers'] == ([48, 49, 55] if model == 'qwen27b' else [31])
    assert protocol['random_seeds'] == [0, 1, 2, 3] and protocol['norm_tolerance'] == .02
    for key in ('vectors', 'reference', 'images'):
        inputs[str(paths[key])] = file_hash(paths[key])
    assert result['status'] == 'complete' and result['model'] == protocol['model'] == model
    for key, path_key in [('protocol_sha256', 'protocol'), ('capture_sha256', 'capture'),
                          ('intervention_records_sha256', 'records')]:
        assert result[key] == file_hash(paths[path_key]), f'Completion hash mismatch: {paths[path_key]}'
    assert capture['protocol'] == protocol
    for key, path_key in [('support', 'support'), ('vectors', 'vectors'), ('reference', 'reference'), ('images', 'images')]:
        assert capture[key] == file_hash(paths[path_key]), f'Capture input changed: {paths[path_key]}'
    families = tracked_json(paths['support'], inputs)['families']
    records = tracked_json(paths['records'], inputs)
    primary = tracked_csv(paths['primary'], inputs)
    frame = pd.DataFrame([{k: v for k, v in r.items() if k not in ('record', 'clean_record')} for r in records])
    validate_trial_grid(frame, families, model)
    assert len(records) == result['condition_records'] and len(families) == result['families'] == protocol['n_families']
    assert len(primary) == protocol['primary_tests'] == (14 if model == 'qwen27b' else 4)
    assert primary.n.eq(len(families)).all() and primary.scope.eq('all_attempted').all()
    assert frame.valid.map(bool_value).all() == bool_value(result['all_controls_valid'])
    assert int(frame.groupby('family_id').valid.all().sum()) == result['fully_valid_families']
    optional = {}
    for name in ('technical_failures', 'valid_family_sensitivity', 'family_metrics', 'subgroup_descriptive',
                 'repair_and_harm_counts', 'secondary_bypass'):
        path = root/'analysis'/f'{name}.csv'
        if path.is_file():
            optional[name] = tracked_csv(path, inputs)
    return dict(model=model, status='validated_complete', issues=[], root=str(root), completion=result,
                protocol=protocol, capture=capture, families=families, records=records, frame=frame,
                primary=primary, optional=optional)


def verify_record_metrics(bundle):
    """Reconstruct baseline pairing and behavioral metrics from saved candidate scores."""
    rows = bundle['records']
    zeros = {(r['family_id'], r['scene_id'], r['variant']): r['record'] for r in rows if r['condition'] == 'zero'}
    for row in rows:
        clean = zeros[row['family_id'], row['scene_id'], row['variant']]
        assert digest(row['clean_record']) == digest(clean), 'Mixed current untreated baseline'
        out = row['record']
        assert clean['gold_semantic'] == out['gold_semantic'] == row['physical_outcome']
        correct = out['predicted_semantic'] == out['gold_semantic']
        baseline = clean['predicted_semantic'] == clean['gold_semantic']
        assert bool_value(row['correct']) == correct and bool_value(row['baseline_correct']) == baseline
        expected = {'accuracy_change': float(correct)-float(baseline),
                    'margin_change': correct_margin(out)-correct_margin(clean),
                    'repaired': not baseline and correct, 'harmed': baseline and not correct,
                    'answer_changed': out['predicted_semantic'] != clean['predicted_semantic']}
        for key, value in expected.items():
            assert abs(float(row[key])-float(value)) < 1e-10, f'Record metric mismatch: {key}'


def reconcile_primary(bundle):
    fresh, means = test_family_contrasts(bundle['frame'], bundle['model'])
    saved = bundle['primary']
    keys = ['contrast', 'metric', 'scope']
    assert not saved.duplicated(keys).any()
    joined = fresh.merge(saved, on=keys, suffixes=('_recomputed', '_saved'), how='outer', indicator=True, validate='one_to_one')
    assert joined['_merge'].eq('both').all()
    columns = ('n', 'mean', 'lower', 'upper', 'p_value', 'q_value')
    for key in columns:
        joined[key+'_absolute_difference'] = abs(joined[key+'_recomputed']-joined[key+'_saved'])
    joined['numeric_match'] = joined[[c+'_absolute_difference' for c in columns]].max(axis=1).le(1e-10)
    decision = confirmation_decisions(saved, bundle['frame'], bundle['model'])
    assert decision == bundle['completion']['decision'], 'Saved decision differs from its original rule'
    return joined, means


def saved_score_vector(record):
    values = record['candidate_logprobs']
    if isinstance(values, dict):
        return np.asarray([values[k] for k in record.get('candidate_labels', ('A', 'B', 'C'))], float)
    return np.asarray(values, float)


def inspect_saved_writes(bundle):
    rows, model = bundle['records'], bundle['model']
    by_key = {(r['family_id'], r['scene_id'], r['variant'], r['condition'], r['random_seed']): r for r in rows}
    tolerance = float(bundle['protocol']['norm_tolerance'])
    flat, trials = [], []
    for row in rows:
        local_failed = False
        local_numeric_mismatch = False
        for layer, audit in row['record']['write_audits'].items():
            has_match = 'matched' in audit
            matched = bool_value(audit['matched']) if has_match else True
            actual = float(audit['actual_norm'])
            target = audit.get('target_norm')
            numerical_error = None if target is None else abs(actual-float(target))/max(float(target), 1e-12)
            local_failed |= not matched
            if has_match and numerical_error is not None:
                # The recorded matched flag drives the original gate; this is an independent check.
                local_numeric_mismatch |= matched != (numerical_error <= tolerance)
            flat.append(dict(model=model, family_id=row['family_id'], scene_id=row['scene_id'], variant=row['variant'],
                condition=row['condition'], random_seed=row['random_seed'], layer=int(layer), action=audit['action'],
                actual_norm=actual, target_norm=target, local_relative_error_saved=audit.get('relative_error'),
                local_relative_error_recomputed=numerical_error, local_matched=matched,
                hidden_norm=audit.get('hidden_norm'), reference_coefficient=audit.get('coefficient')))
        cross_failed = False
        cross_error = target_actual = actual = None
        cross_field_consistent = True
        ref = reference_for_condition(model, row['condition'])
        if ref:
            name, layer = ref
            target_row = by_key[row['family_id'], row['scene_id'], row['variant'], name, -1]
            target_actual = float(target_row['record']['write_audits'][str(layer)]['actual_norm'])
            actual = float(row['record']['write_audits'][str(layer)]['actual_norm'])
            cross_error = abs(actual-target_actual)/max(target_actual, 1e-12)
            cross_failed = cross_error > tolerance
            cross_field_consistent = (row.get('paired_reference_condition') == name
                and abs(float(row['paired_reference_actual_norm'])-target_actual) < 1e-10
                and abs(float(row['paired_actual_relative_error'])-cross_error) < 1e-10)
        self_failed = False
        self_gap = None
        if row['condition'].startswith('self_'):
            a, b = saved_score_vector(row['record']), saved_score_vector(row['clean_record'])
            self_gap = float(np.max(abs((a-a.mean())-(b-b.mean()))))
            self_failed = self_gap > .15 or row['record']['predicted_semantic'] != row['clean_record']['predicted_semantic']
        recomputed_valid = not (local_failed or cross_failed or self_failed)
        stored_valid = bool_value(row['valid'])
        reasons = []
        if local_failed: reasons.append('local_norm_match')
        if cross_failed: reasons.append('cross_forward_norm_match')
        if self_failed: reasons.append('self_clamp_parity')
        if stored_valid != recomputed_valid: reasons.append('stored_valid_flag_inconsistent')
        if not cross_field_consistent: reasons.append('saved_cross_audit_inconsistent')
        if local_numeric_mismatch: reasons.append('local_flag_numeric_disagreement')
        trials.append(dict(model=model, family_id=row['family_id'], scene_id=row['scene_id'], variant=row['variant'],
            stratum=row['stratum'], style=row['style'], physical_outcome=row['physical_outcome'],
            condition=row['condition'], random_seed=row['random_seed'], stored_valid=stored_valid,
            recomputed_original_gate_valid=recomputed_valid, local_match_failed=local_failed,
            cross_match_failed=cross_failed, self_parity_failed=self_failed,
            saved_fields_consistent=stored_valid == recomputed_valid and cross_field_consistent and not local_numeric_mismatch,
            failure_reasons=';'.join(reasons) or 'none',
            actual_delta_norm=actual, executed_target_delta_norm=target_actual,
            absolute_norm_gap=None if actual is None else abs(actual-target_actual),
            cross_relative_error=cross_error, self_centered_score_gap=self_gap))
    return pd.DataFrame(flat), pd.DataFrame(trials)


def condition_failure_summary(trials):
    summaries = []
    for condition, sub in trials.groupby('condition'):
        failed = sub[~sub.stored_valid]
        summaries.append(dict(condition=condition, attempted_records=len(sub), failed_records=len(failed),
            affected_families=failed.family_id.nunique(), affected_scene_mappings=failed[['scene_id', 'variant']].drop_duplicates().shape[0],
            local_match_failures=int(sub.local_match_failed.sum()), cross_match_failures=int(sub.cross_match_failed.sum()),
            both_norm_checks_failed=int((sub.local_match_failed & sub.cross_match_failed).sum()),
            self_parity_failures=int(sub.self_parity_failed.sum()), inconsistent_audit_records=int((~sub.saved_fields_consistent).sum())))
    return pd.DataFrame(summaries)


def path_diagnostics(bundle, family_means):
    assert bundle['model'] == 'qwen27b'
    frame, tests, result = bundle['frame'], bundle['primary'], bundle['completion']
    gates, sensitivity, influences = [], [], []
    for path, start, layer in [('ua', 'u', 49), ('ub', 'u', 55), ('ab', 'a', 55)]:
        required = [start, start+'_random', path+'_equal', path+'_block', f'self_{layer}', f'self_random_{layer}']
        relevant = frame[frame.condition.isin(required)]
        valid_ids = set(relevant.groupby('family_id').valid.all().loc[lambda x:x].index)
        all_ids = set(frame.family_id)
        for metric in ('accuracy_change', 'margin_change'):
            row = tests[tests.contrast.eq(path+'_specific_loss') & tests.metric.eq(metric)].iloc[0]
            downstream = frame[frame.condition.isin([path+'_equal', path+'_block', f'self_{layer}', f'self_random_{layer}'])]
            gates.append(dict(path=path, metric=metric, upstream_repair_confirmed=result['decision'][metric]['repair_confirmed'][start],
                statistical_pass=bool(row.lower > 0 and row.q_value < .05), downstream_controls_valid=bool(downstream.valid.all()),
                original_confirmation=result['decision'][metric]['selective_dependence_confirmed'][path],
                all_families=len(all_ids), path_valid_families=len(valid_ids), path_invalid_families=len(all_ids-valid_ids)))
            left = family_means[family_means.condition.eq(path+'_equal')].set_index('family_id')[metric]
            right = family_means[family_means.condition.eq(path+'_block')].set_index('family_id')[metric]
            effects = left-right
            assert effects.notna().all() and len(effects) == len(all_ids)
            for scope, ids in [('all_attempted', all_ids), ('path_controls_valid_posthoc', valid_ids),
                               ('path_controls_invalid_descriptive', all_ids-valid_ids)]:
                values = effects[effects.index.isin(ids)].to_numpy(float)
                if len(values):
                    ci = bootstrap(values, ['completion_audit', path, metric, scope])
                    sensitivity.append(dict(path=path, metric=metric, scope=scope,
                        **{k: ci[k] for k in ('n', 'mean', 'lower', 'upper')}, original_gate_unchanged=True))
            influences.extend(dict(path=path, metric=metric, family_id=fid, effect=float(value),
                path_controls_valid=fid in valid_ids, contribution_to_all_family_mean=float(value)/len(all_ids))
                for fid, value in effects.items())
    return pd.DataFrame(gates), pd.DataFrame(sensitivity), pd.DataFrame(influences)


def subgroup_summary(bundle):
    frame = bundle['frame']
    output = []
    for group in ('stratum', 'physical_outcome', 'baseline_correct', 'style', 'variant'):
        for (value, condition), sub in frame.groupby([group, 'condition']):
            metrics = ['accuracy_change', 'margin_change', 'correct', 'baseline_correct', 'repaired', 'harmed']
            # Avoid using a grouping variable as both a column and index.
            units = sub.groupby(['family_id', 'scene_id', 'variant'])[metrics].mean().reset_index()
            means = units.groupby('family_id')[metrics].mean()
            ci = bootstrap(means.accuracy_change.to_numpy(float), ['subgroup', bundle['model'], group, str(value), condition])
            output.append(dict(model=bundle['model'], group=group, value=str(value), condition=condition,
                families=len(means), scene_mapping_units=len(units),
                baseline_accuracy=float(means.baseline_correct.mean()), accuracy=float(means.correct.mean()),
                accuracy_change=float(means.accuracy_change.mean()), margin_change=float(means.margin_change.mean()),
                accuracy_lower=ci['lower'], accuracy_upper=ci['upper'],
                original_wrong_units=float((1-units.baseline_correct).sum()), original_correct_units=float(units.baseline_correct.sum()),
                repaired_units_seed_average=float(units.repaired.sum()), harmed_units_seed_average=float(units.harmed.sum()),
                interpretation='posthoc_descriptive_family_aggregation_no_new_confirmation'))
    return pd.DataFrame(output)


def summarize_archived_readout(frame, threshold):
    assert not frame.duplicated(['scene_id', 'repeat']).any()
    assert frame.groupby('scene_id').size().eq(3).all()
    assert frame.groupby('scene_id').repeat.apply(lambda x: set(x) == {0, 1, 2}).all()
    assert frame.scene_id.nunique() == 19
    outcome = lambda x: 'left' if x > threshold else 'right' if x < -threshold else 'balanced'
    columns = ['archived_readout', 'current_native_readout', 'current_fp16_pipeline_readout',
               'archived_minus_current', 'storage_roundtrip_change']
    assert np.isfinite(frame[columns].to_numpy(float)).all()
    assert abs(frame.archived_readout-frame.current_native_readout-frame.archived_minus_current).max() < 1e-8
    assert abs(frame.current_fp16_pipeline_readout-frame.current_native_readout-frame.storage_roundtrip_change).max() < 1e-8
    rows = []
    for sid, sub in frame.groupby('scene_id'):
        assert sub.archived_readout.nunique() == 1
        native_gap = abs(sub.archived_readout-sub.current_native_readout)
        storage_shift = abs(sub.storage_roundtrip_change)
        remaining_gap = abs(sub.archived_readout-sub.current_fp16_pipeline_readout)
        old_class = outcome(float(sub.archived_readout.iloc[0]))
        current_classes = sub.current_native_readout.map(outcome)
        rows.append(dict(scene_id=sid, repeats=3, archived_readout=float(sub.archived_readout.iloc[0]),
            current_native_readout_mean=float(sub.current_native_readout.mean()),
            current_fp16_readout_mean=float(sub.current_fp16_pipeline_readout.mean()),
            mean_absolute_archive_gap=float(native_gap.mean()), maximum_absolute_archive_gap=float(native_gap.max()),
            mean_absolute_storage_shift=float(storage_shift.mean()), maximum_absolute_storage_shift=float(storage_shift.max()),
            mean_absolute_residual_after_storage=float(remaining_gap.mean()),
            maximum_absolute_residual_after_storage=float(remaining_gap.max()),
            archived_class=old_class, current_classes='|'.join(sorted(set(current_classes))),
            any_class_changed_from_archive=bool(current_classes.ne(old_class).any()),
            within_current_repeat_class_changed=bool(current_classes.nunique() > 1)))
    by_scene = pd.DataFrame(rows)
    summary = dict(scenes=19, repeat_rows=len(frame),
        mean_absolute_archive_gap=float(by_scene.mean_absolute_archive_gap.mean()),
        maximum_absolute_archive_gap=float(by_scene.maximum_absolute_archive_gap.max()),
        mean_absolute_storage_shift=float(by_scene.mean_absolute_storage_shift.mean()),
        maximum_absolute_storage_shift=float(by_scene.maximum_absolute_storage_shift.max()),
        mean_absolute_residual_after_storage=float(by_scene.mean_absolute_residual_after_storage.mean()),
        class_changed_scenes=int(by_scene.any_class_changed_from_archive.sum()),
        within_current_repeat_class_changed_scenes=int(by_scene.within_current_repeat_class_changed.sum()))
    return by_scene, summary


def load_repeat_result(root, project, model, slug, inputs):
    root = Path(root)
    paths = {'completion': root/'analysis/RUN_COMPLETE.json', 'protocol': root/'protocol.json',
             'identity': root/'repeat_identity.json', 'pairs': root/'analysis/within_runtime_pairs.csv',
             'means': root/'analysis/within_runtime_scene_means.csv',
             'historical': root/'analysis/historical_scene_mean_comparison.csv'}
    missing = [str(p) for p in paths.values() if not p.is_file()]
    if missing:
        return dict(model=model, status='missing_inputs', issues=missing)
    completion = tracked_json(paths['completion'], inputs)
    protocol = tracked_json(paths['protocol'], inputs)
    identity = tracked_json(paths['identity'], inputs)
    assert completion['status'] == 'complete' and completion['model'] == protocol['model'] == model
    assert identity['protocol'] == protocol
    assert completion['development_scenes'] == 19 and completion['mappings_per_scene'] == 6
    assert completion['repeats'] == 3 and completion['forward_count'] == 342 and completion['probe_refit'] is False
    old = Path(project)/'results/cross_model_readout_correction_v2/models'/slug
    for key, name in [('probe', 'frozen_probe.json'), ('old_protocol', 'protocol.json'), ('old_runtime', 'runtime_identity.json')]:
        path = old/name
        assert path.is_file(), f'Missing frozen diagnostic input: {path}'
        inputs[str(path)] = file_hash(path)
        assert identity[key] == inputs[str(path)], f'Frozen readout input changed: {path}'
    old_protocol = read_json(old/'protocol.json')
    threshold = float(old_protocol['balance_threshold'])
    pairs = tracked_csv(paths['pairs'], inputs)
    means = tracked_csv(paths['means'], inputs)
    assert len(pairs) == 342 and pairs.scene_id.nunique() == 19
    assert not pairs.duplicated(['scene_id', 'variant', 'repeat_a', 'repeat_b']).any()
    assert pairs.groupby(['scene_id', 'variant']).size().eq(3).all()
    assert pairs.groupby('scene_id').variant.nunique().eq(6).all()
    for _, sub in pairs.groupby(['scene_id', 'variant']):
        assert set(zip(sub.repeat_a, sub.repeat_b)) == {(0, 1), (0, 2), (1, 2)}
    assert len(means) == 57 and means.scene_id.nunique() == 19
    assert not means.duplicated(['scene_id', 'repeat_a', 'repeat_b']).any()
    for key in ('readout_over_tolerance', 'decoded_outcome_changed', 'answer_changed'):
        pairs[key] = pairs[key].map(bool_value)
    means['scene_mean_class_changed'] = means.scene_mean_class_changed.map(bool_value)
    for result_key, column in [('readout_over_tolerance', 'readout_over_tolerance'),
                               ('any_answer_changed', 'answer_changed'), ('any_readout_class_changed', 'decoded_outcome_changed')]:
        assert bool_value(completion[result_key]) == bool(pairs[column].any())
    assert bool_value(completion['any_scene_mean_class_changed']) == bool(means.scene_mean_class_changed.any())
    historical = tracked_csv(paths['historical'], inputs)
    by_scene, summary = pd.DataFrame(), {}
    if not historical.empty:
        by_scene, summary = summarize_archived_readout(historical, threshold)
        assert set(by_scene.scene_id) == set(pairs.scene_id)
    config_rows = []
    archive_inputs = root/'archive_inputs.json'
    if archive_inputs.is_file():
        archived_identity = tracked_json(archive_inputs, inputs)['identity']
        current = identity['runtime']
        # Show available configuration fields; differences are clues, not a causal attribution.
        for source_name, value in [('historical_capture', archived_identity), ('current_repeat', current)]:
            for key, v in value.items():
                if any(token in key.lower() for token in ('batch', 'dtype', 'layer', 'version', 'position', 'pool', 'attention', 'cuda', 'torch', 'transformer', 'gpu')):
                    if key != 'toolkit':
                        config_rows.append(dict(model=model, source=source_name, field=key, value=json.dumps(v, ensure_ascii=False)))
    repeat_summary = dict(model=model, scenes=19, forwards=342,
        maximum_hidden_change=float(pairs.hidden_max_change.max()),
        maximum_readout_change=float(pairs.readout_absolute_change.max()),
        maximum_centered_score_change=float(pairs.centered_score_max_change.max()),
        any_answer_changed=bool(pairs.answer_changed.any()),
        any_readout_class_changed=bool(pairs.decoded_outcome_changed.any()))
    return dict(model=model, status='validated_complete', issues=[], completion=completion,
        repeat_summary=repeat_summary, by_scene=by_scene, archive_summary=summary,
        historical=historical, config_rows=config_rows)


def csv_markdown(frame, columns=None, limit=40):
    if frame.empty:
        return '无记录。'
    shown = frame if columns is None else frame[columns]
    shown = shown.head(limit)
    escape = lambda x: str(x).replace('|', '/').replace('\n', ' ')
    lines = ['| '+' | '.join(map(escape, shown.columns))+' |', '| '+' | '.join(['---']*len(shown.columns))+' |']
    for row in shown.itertuples(index=False, name=None):
        lines.append('| '+' | '.join(escape(f'{v:.6g}' if isinstance(v, float) else v) for v in row)+' |')
    if len(frame) > limit:
        lines += ['', f'此处显示前 {limit} 行，完整 {len(frame)} 行保存在 CSV。']
    return '\n'.join(lines)

Load shared validation utilities:  20%|##        | 2/10 [00:00<?, ?cell/s]

In [5]:
%%cell_progress 4/10 Locate the completed experiments and set a separate audit destination
RUN_ID='main'  # 本次核查输出名称。
EXPERIMENT_RUN_ID='main'  # 上一轮 Qwen/Gemma 新场景实验的运行名称。
REPEAT_RUN_ID='main'  # 上一轮两份读出重复性诊断的运行名称。
AUTO_DOWNLOAD=True  # 最后自动下载一个结果包，便于带回完整明细。
BASE=PROJECT_ROOT/'results/cross_model_independent_confirmation'
OUTPUT_ROOT=BASE/'completion_audit'/RUN_ID
OUTPUT_ROOT.mkdir(parents=True,exist_ok=True)
MODEL_SLUGS={'qwen27b':'Qwen__Qwen3.5-27B__373612cb','gemma12b':'google__gemma-4-12B-it','qwen9b':'Qwen__Qwen3.5-9B'}
SCIENCE_ROOTS={
    'qwen27b':BASE/'qwen_three_path'/EXPERIMENT_RUN_ID/MODEL_SLUGS['qwen27b'],
    'gemma12b':BASE/'gemma_l31_candidate'/EXPERIMENT_RUN_ID/MODEL_SLUGS['gemma12b'],
}
assert all(OUTPUT_ROOT.resolve()!=p.resolve() and p.resolve() not in OUTPUT_ROOT.resolve().parents for p in SCIENCE_ROOTS.values())
inputs={};coverage=[];science={};repeat_results={};export_files=set();report_sections=[]
pd.set_option('display.max_columns',40)
pd.set_option('display.width',180)

def export_csv(name,frame):
    path=OUTPUT_ROOT/name
    frame.to_csv(path,index=False,encoding='utf-8-sig')
    export_files.add(path)
    return path

def export_json(name,value):
    path=OUTPUT_ROOT/name;save_json(path,value);export_files.add(path)
    return path

def show(title,frame,limit=40):
    print('\n'+title)
    if frame.empty:
        print('无记录。');return
    with pd.option_context('display.max_rows',limit+2,'display.max_columns',None,'display.max_colwidth',80):
        display(frame.head(limit))
    if len(frame)>limit:print(f'这里显示前 {limit} 行；完整 {len(frame)} 行会放入结果包。')

export_json('audit_configuration.json',dict(schema='independent-results-completion-audit-1.0',implementation=IMPLEMENTATION_SHA256,
    experiment_run=EXPERIMENT_RUN_ID,repeat_run=REPEAT_RUN_ID,changes_to_source_results=False,
    scope='CPU inspection of saved records; no inference; no new confirmatory tests',numpy=np.__version__,pandas=pd.__version__))
print('本 notebook 一次读取所有相关模型，无需切换 MODEL_KEY，无需 GPU。')
print('核查输出：',OUTPUT_ROOT)

Locate the completed experiments and set a separate audit destination:  30%|###       | 3/10 [00:00<?, ?cell/s…

本 notebook 一次读取所有相关模型，无需切换 MODEL_KEY，无需 GPU。
核查输出： /content/drive/MyDrive/VisualTorque/results/cross_model_independent_confirmation/completion_audit/main

In [6]:
%%cell_progress 5/10 Verify the original records, pairings, primary statistics and saved decisions
numeric_checks=[]
for model,root in tqdm(SCIENCE_ROOTS.items(),desc='Reading completed science experiments'):
    try:
        bundle=load_science_result(root,model,inputs)
        if bundle['status']=='validated_complete':
            verify_record_metrics(bundle)
            comparison,family_means=reconcile_primary(bundle)
            bundle['primary_numeric_match']=bool(comparison.numeric_match.all())
            bundle['family_means_recomputed']=family_means
            export_csv(model+'_primary_reproduction_check.csv',comparison)
            export_csv(model+'_original_primary_tests.csv',bundle['primary'])
            export_json(model+'_original_completion.json',bundle['completion'])
            for name,table in bundle['optional'].items():export_csv(model+'_original_'+name+'.csv',table)
            numeric_checks.append(dict(model=model,primary_tests=len(comparison),all_primary_numbers_match=bool(comparison.numeric_match.all()),
                original_decision_preserved=True,independent_families=len(bundle['families']),records=len(bundle['records'])))
    except (AssertionError,KeyError,ValueError,TypeError,OSError) as error:
        bundle=dict(model=model,status='input_integrity_error',issues=[type(error).__name__+': '+str(error)])
    science[model]=bundle
    coverage.append(dict(stage='science',model=model,status=bundle['status'],source=str(root),issues='; '.join(bundle['issues'])))
    if bundle['status']!='validated_complete':print(model,':',bundle['status'],bundle['issues'])
export_csv('primary_statistics_reproduction.csv',pd.DataFrame(numeric_checks))
show('原主结果与完整记录的核对',pd.DataFrame(numeric_checks))
report_sections.append('## 原结果一致性\n\n'+csv_markdown(pd.DataFrame(numeric_checks)))
print('这一步复核原来的 14/4 项检验及判定，不改变检验族、方向、样本量或容差。')

Verify the original records, pairings, primary statistics and saved decisions:  40%|####      | 4/10 [00:00<?,…

Reading completed science experiments:   0%|          | 0/2 [00:00<?, ?it/s]

原主结果与完整记录的核对

      model  primary_tests  all_primary_numbers_match  original_decision_preserved  independent_families  records
0   qwen27b             14                       True                         True                    64    17920
1  gemma12b              4                       True                         True                    64     3072

这一步复核原来的 14/4 项检验及判定，不改变检验族、方向、样本量或容差。

In [7]:
%%cell_progress 6/10 Identify every failed Qwen control and its actual physical edit size
qwen=science['qwen27b']
qwen_diagnosis=dict(status=qwen['status'])
if qwen['status']=='validated_complete':
    operations,trials=inspect_saved_writes(qwen)
    failure_summary=condition_failure_summary(trials)
    failed=trials[~trials.stored_valid|~trials.saved_fields_consistent].copy()
    export_csv('qwen_all_write_operations.csv',operations)
    export_csv('qwen_all_trial_validity.csv',trials)
    export_csv('qwen_failure_counts_by_condition.csv',failure_summary)
    export_csv('qwen_failed_trial_details.csv',failed)
    keys={(r.family_id,r.scene_id,r.variant,r.condition,int(r.random_seed)) for r in failed.itertuples()}
    failed_records=[r for r in qwen['records'] if (r['family_id'],r['scene_id'],r['variant'],r['condition'],r['random_seed']) in keys]
    export_json('qwen_failed_records_with_write_audits.json',failed_records)
    failed_ids=set(failed.family_id)
    export_json('qwen_failed_family_physics.json',[f for f in qwen['families'] if f['family_id'] in failed_ids])
    for condition in ('ua_equal','ub_equal','ab_equal'):
        sub=trials[trials.condition.eq(condition)]
        qwen_diagnosis[condition]=dict(attempted=len(sub),failed=int((~sub.stored_valid).sum()),
            affected_families=int(sub.loc[~sub.stored_valid,'family_id'].nunique()),
            local_match_failures=int(sub.local_match_failed.sum()),cross_match_failures=int(sub.cross_match_failed.sum()),
            inconsistent_audits=int((~sub.saved_fields_consistent).sum()))
    qwen_diagnosis.update(all_original_failed_records=int((~trials.stored_valid).sum()),
        all_affected_families=int(trials.loc[~trials.stored_valid,'family_id'].nunique()),
        all_audit_fields_consistent=bool(trials.saved_fields_consistent.all()),
        originally_fully_valid_families=qwen['completion']['fully_valid_families'],
        original_decision=qwen['completion']['decision'])
    qwen_diagnosis['status']='diagnosed_from_saved_records'
    show('全部条件的失败条数（local/cross 可能同时失败，不能直接相加）',failure_summary,limit=40)
    show('失败明细：local=单次修改内部，cross=相对实际执行的目标条件',failed[[
        'family_id','scene_id','variant','condition','random_seed','failure_reasons',
        'executed_target_delta_norm','actual_delta_norm','absolute_norm_gap','cross_relative_error']],limit=25)
    bad_ops=operations.merge(failed[['family_id','scene_id','variant','condition','random_seed']],
        on=['family_id','scene_id','variant','condition','random_seed'],how='inner',validate='many_to_one')
    export_csv('qwen_failed_write_operations.csv',bad_ops)
    show('失败记录对应的每层写入审计',bad_ops,limit=25)
    ub=qwen_diagnosis['ub_equal']
    print(f'L48→L55：{ub["failed"]}/{ub["attempted"]} 条随机移除记录未通过，涉及 {ub["affected_families"]} 个物理家族。')
    print(f'单次写入内部未匹配 {ub["local_match_failures"]} 条；与实际执行的指定阻断不匹配 {ub["cross_match_failures"]} 条。')
    print('以下结果只定位失败原因。原 2% 容差与原确认状态保持不变。')
    report_sections.append('## Qwen 随机对照的失败原因\n\n'+csv_markdown(failure_summary)+'\n\n'+
        f'L48→L55 随机移除失败 {ub["failed"]}/{ub["attempted"]} 条，涉及 {ub["affected_families"]} 个家族。\n\n'+
        '单次匹配失败与跨前向匹配失败分别计数，可能重叠。明细及原始 write_audits 已打包。')
export_json('qwen_technical_diagnosis.json',qwen_diagnosis)

Identify every failed Qwen control and its actual physical edit size:  50%|#####     | 5/10 [00:00<?, ?cell/s]

全部条件的失败条数（local/cross 可能同时失败，不能直接相加）

,condition,attempted_records,failed_records,affected_families,affected_scene_mappings,local_match_failures,cross_match_failures,both_norm_checks_failed,self_parity_failures,inconsistent_audit_records
0,a,512,0,0,0,0,0,0,0,0
1,a_random,2048,0,0,0,0,0,0,0,0
2,ab_block,512,0,0,0,0,0,0,0,0
3,ab_coordinate,512,0,0,0,0,0,0,0,0
4,ab_equal,2048,0,0,0,0,0,0,0,0
5,b,512,0,0,0,0,0,0,0,0
6,bypass,512,0,0,0,0,0,0,0,0
7,self_49,512,0,0,0,0,0,0,0,0
8,self_55,512,0,0,0,0,0,0,0,0
9,self_random_49,512,0,0,0,0,0,0,0,0
10,self_random_55,512,0,0,0,0,0,0,0,0
11,u,512,0,0,0,0,0,0,0,0
12,u_random,2048,0,0,0,0,0,0,0,0
13,ua_block,512,0,0,0,0,0,0,0,0
14,ua_coordinate,512,0,0,0,0,0,0,0,0
15,ua_equal,2048,0,0,0,0,0,0,0,0
16,ub_block,512,0,0,0,0,0,0,0,0
17,ub_coordinate,512,0,0,0,0,0,0,0,0
18,ub_equal,2048,1,1,1,1,1,1,0,0
19,zero,512,0,0,0,0,0,0,0,0

失败明细：local=单次修改内部，cross=相对实际执行的目标条件

,family_id,scene_id,variant,condition,random_seed,failure_reasons,executed_target_delta_norm,actual_delta_norm,absolute_norm_gap,cross_relative_error
6783,repair_50b977d3090a9efd6589,repair_50b977d3090a9efd6589__m0__standard,reverse,ub_equal,3,local_norm_match;cross_forward_norm_match,0.000422,0.000449,0.000027,0.062917

失败记录对应的每层写入审计

,model,family_id,scene_id,variant,condition,random_seed,layer,action,actual_norm,target_norm,local_relative_error_saved,local_relative_error_recomputed,local_matched,hidden_norm,reference_coefficient
0,qwen27b,repair_50b977d3090a9efd6589,repair_50b977d3090a9efd6589__m0__standard,reverse,ub_equal,3,48,add,17.141872,NaN,NaN,NaN,True,88.717651,NaN
1,qwen27b,repair_50b977d3090a9efd6589,repair_50b977d3090a9efd6589__m0__standard,reverse,ub_equal,3,55,equal_remove,0.000449,0.000422,0.062917,0.062917,False,153.708588,0.003856

L48→L55：1/2048 条随机移除记录未通过，涉及 1 个物理家族。
单次写入内部未匹配 1 条；与实际执行的指定阻断不匹配 1 条。
以下结果只定位失败原因。原 2% 容差与原确认状态保持不变。

PosixPath('/content/drive/MyDrive/VisualTorque/results/cross_model_independent_confirmation/completion_audit/main/qwen_technical_diagnosis.json')

PosixPath('/content/drive/MyDrive/VisualTorque/results/cross_model_independent_confirmation/completion_audit/main/qwen_technical_diagnosis.json')

In [8]:
%%cell_progress 7/10 Show path-specific sensitivity without changing the original confirmation gates
if qwen['status']=='validated_complete':
    gates,sensitivity,influence=path_diagnostics(qwen,qwen['family_means_recomputed'])
    export_csv('qwen_original_path_gates.csv',gates)
    export_csv('qwen_path_valid_sensitivity_posthoc.csv',sensitivity)
    export_csv('qwen_family_effect_contributions.csv',influence)
    show('原来的三路径判定，逐项拆开显示',gates)
    view=sensitivity[sensitivity.metric.eq('accuracy_change')].copy()
    for column in ('mean','lower','upper'):view[column+'_percentage_points']=100*view[column]
    show('准确率：全体、路径对照有效组、路径对照无效组（事后敏感性）',
        view[['path','scope','n','mean_percentage_points','lower_percentage_points','upper_percentage_points']])
    print('只保留有效家族会改变分析样本；上述事后区间不能把原来的 False 改成 True。')
    report_sections.append('## 原判定与事后敏感性\n\n'+csv_markdown(gates)+'\n\n'+
        csv_markdown(view[['path','scope','n','mean_percentage_points','lower_percentage_points','upper_percentage_points']])+\
        '\n\n路径有效组是基于技术检查的事后敏感性分析，不替代原全体家族的主结果；失败组的区间仅用于描述。')

Show path-specific sensitivity without changing the original confirmation gates:  60%|######    | 6/10 [00:00<…

原来的三路径判定，逐项拆开显示

  path           metric  upstream_repair_confirmed  statistical_pass  downstream_controls_valid  original_confirmation  all_families  path_valid_families  path_invalid_families
0   ua  accuracy_change                       True              True                       True                   True            64                   64                      0
1   ua    margin_change                       True              True                       True                   True            64                   64                      0
2   ub  accuracy_change                       True              True                      False                  False            64                   63                      1
3   ub    margin_change                       True              True                      False                  False            64                   63                      1
4   ab  accuracy_change                       True              True                       True                   True            64                   64                      0
5   ab    margin_change                       True              True                       True                   True            64                   64                      0

准确率：全体、路径对照有效组、路径对照无效组（事后敏感性）

   path                              scope   n  mean_percentage_points  lower_percentage_points  upper_percentage_points
0    ua                      all_attempted  64               10.644531                 8.007812                13.378906
1    ua        path_controls_valid_posthoc  64               10.644531                 7.958984                13.378906
4    ub                      all_attempted  64                3.564453                 1.562500                 5.810547
5    ub        path_controls_valid_posthoc  63                3.670635                 1.587302                 5.853175
6    ub  path_controls_invalid_descriptive   1               -3.125000                -3.125000                -3.125000
10   ab                      all_attempted  64                3.955078                 1.367188                 6.640625
11   ab        path_controls_valid_posthoc  64                3.955078                 1.367188                 6.591797

只保留有效家族会改变分析样本；上述事后区间不能把原来的 False 改成 True。

In [9]:
%%cell_progress 8/10 Summarize which physical conditions improve, including repairs and harms
stratum_labels={'equal_weight_distance':'重量相同、距离不同','weight_distance_conflict':'重量与距离线索冲突',
    'multi_stack_sum':'多个物体，需要求和','aligned_cues':'重量和距离线索一致'}
for model,bundle in science.items():
    if bundle['status']!='validated_complete':continue
    summary=subgroup_summary(bundle)
    export_csv(model+'_all_subgroups_descriptive.csv',summary)
    selected=('u','a','b','bypass') if model=='qwen27b' else ('targeted','random')
    main=summary[summary.group.eq('stratum')&summary.condition.isin(selected)].copy()
    main['physical_condition']=main.value.map(stratum_labels).fillna(main.value)
    main['accuracy_change_pp']=100*main.accuracy_change
    main['accuracy_lower_pp']=100*main.accuracy_lower;main['accuracy_upper_pp']=100*main.accuracy_upper
    columns=['physical_condition','condition','families','scene_mapping_units','accuracy_change_pp',
             'accuracy_lower_pp','accuracy_upper_pp','repaired_units_seed_average','harmed_units_seed_average']
    show(model+'：四类物理场景分别表现如何',main[columns])
    show(model+'：左右、镜像配色与选项映射的完整描述另存 CSV',
        summary[summary.group.eq('physical_outcome')&summary.condition.isin(selected)][
            ['value','condition','families','scene_mapping_units','accuracy_change','margin_change']])
    report_sections.append('## '+model+'：物理条件分组\n\n'+csv_markdown(main[columns])+\
        '\n\n各子组保留家族内配对与种子平均；区间为事后描述，不重新筛选候选或改变主结论。')

Summarize which physical conditions improve, including repairs and harms:  70%|#######   | 7/10 [00:00<?, ?cel…

qwen27b：四类物理场景分别表现如何

   physical_condition condition  families  scene_mapping_units  accuracy_change_pp  accuracy_lower_pp  accuracy_upper_pp  repaired_units_seed_average  harmed_units_seed_average
0           重量和距离线索一致         a        16                  128            14.06250            7.81250           20.31250                         18.0                        0.0
5           重量和距离线索一致         b        16                  128            17.18750           10.15625           25.00000                         22.0                        0.0
6           重量和距离线索一致    bypass        16                  128            17.96875           10.93750           25.78125                         23.0                        0.0
11          重量和距离线索一致         u        16                  128             9.37500            3.12500           17.18750                         12.0                        0.0
20          重量相同、距离不同         a        16                  128            20.31250           13.28125           27.34375                         26.0                        0.0
25          重量相同、距离不同         b        16                  128            21.87500           14.84375           29.68750                         28.0                        0.0
26          重量相同、距离不同    bypass        16                  128            22.65625           14.06250           31.25000                         30.0                        1.0
31          重量相同、距离不同         u        16                  128            16.40625           10.15625           22.65625                         21.0                        0.0
40          多个物体，需要求和         a        16                  128            14.84375            9.37500           20.31250                         19.0                        0.0
45          多个物体，需要求和         b        16                  128            17.96875           12.50000           22.65625                         23.0                        0.0
46          多个物体，需要求和    bypass        16                  128            18.75000           14.06250           22.65625                         24.0                        0.0
51          多个物体，需要求和         u        16                  128            15.62500           10.15625           21.09375                         20.0                        0.0
60          重量与距离线索冲突         a        16                  128             6.25000            2.34375           10.93750                          8.0                        0.0
65          重量与距离线索冲突         b        16                  128            10.93750            5.46875           16.40625                         14.0                        0.0
66          重量与距离线索冲突    bypass        16                  128            14.84375            8.59375           20.31250                         19.0                        0.0
71          重量与距离线索冲突         u        16                  128             6.25000            2.34375           10.93750                          8.0                        0.0

qwen27b：左右、镜像配色与选项映射的完整描述另存 CSV

     value condition  families  scene_mapping_units  accuracy_change  margin_change
80    left         a        64                  256         0.035156       0.491699
85    left         b        64                  256         0.031250       0.560547
86    left    bypass        64                  256         0.035156       0.837891
91    left         u        64                  256         0.050781       0.767578
100  right         a        64                  256         0.242188       0.591309
105  right         b        64                  256         0.308594       0.792969
106  right    bypass        64                  256         0.335938       0.832031
111  right         u        64                  256         0.187500       0.483887

gemma12b：四类物理场景分别表现如何

   physical_condition condition  families  scene_mapping_units  accuracy_change_pp  accuracy_lower_pp  accuracy_upper_pp  repaired_units_seed_average  harmed_units_seed_average
0           重量和距离线索一致    random        16                  128           -1.757812          -3.125000          -0.781250                         0.00                       2.25
1           重量和距离线索一致  targeted        16                  128            0.000000           0.000000           0.000000                         0.00                       0.00
3           重量相同、距离不同    random        16                  128            1.171875          -0.585938           3.710938                         2.00                       0.50
4           重量相同、距离不同  targeted        16                  128            0.781250           0.000000           2.343750                         1.00                       0.00
6           多个物体，需要求和    random        16                  128            1.367188          -2.148438           5.468750                         5.75                       4.00
7           多个物体，需要求和  targeted        16                  128            4.687500           1.562500           8.593750                         6.00                       0.00
9           重量与距离线索冲突    random        16                  128            2.539062           1.367188           3.906250                         3.25                       0.00
10          重量与距离线索冲突  targeted        16                  128            0.000000           0.000000           0.000000                         0.00                       0.00

gemma12b：左右、镜像配色与选项映射的完整描述另存 CSV

    value condition  families  scene_mapping_units  accuracy_change  margin_change
12   left    random        64                  256         0.000977      -0.038293
13   left  targeted        64                  256         0.007812       0.161865
15  right    random        64                  256         0.015625       0.070938
16  right  targeted        64                  256         0.019531       0.168091

In [10]:
%%cell_progress 9/10 Read all nineteen historical readout comparisons for both models
repeat_summary=[];archive_summary=[];config_rows=[]
for model in ('gemma12b','qwen9b'):
    slug=MODEL_SLUGS[model];root=BASE/'readout_repeatability'/REPEAT_RUN_ID/slug
    try:
        item=load_repeat_result(root,PROJECT_ROOT,model,slug,inputs)
        if item['status']=='validated_complete':
            repeat_summary.append(item['repeat_summary'])
            if item['archive_summary']:archive_summary.append(dict(model=model,**item['archive_summary']))
            config_rows.extend(item['config_rows'])
            export_csv(model+'_historical_readout_all_57_rows.csv',item['historical'])
            export_csv(model+'_historical_readout_19_scene_summary.csv',item['by_scene'])
            export_json(model+'_repeat_original_completion.json',item['completion'])
            shown=item['by_scene'].sort_values('maximum_absolute_archive_gap',ascending=False) if not item['by_scene'].empty else item['by_scene']
            show(model+'：完整 19 场景的旧新读出差异',shown,limit=19)
    except (AssertionError,KeyError,ValueError,TypeError,OSError) as error:
        item=dict(model=model,status='input_integrity_error',issues=[type(error).__name__+': '+str(error)])
    repeat_results[model]=item
    coverage.append(dict(stage='repeatability',model=model,status=item['status'],source=str(root),issues='; '.join(item['issues'])))
    if item['status']!='validated_complete':print(model,':',item['status'],item['issues'])
export_csv('readout_current_repeatability_verified.csv',pd.DataFrame(repeat_summary))
export_csv('readout_archive_difference_summary.csv',pd.DataFrame(archive_summary))
export_csv('readout_available_capture_configurations.csv',pd.DataFrame(config_rows))
show('当前配置的重复性',pd.DataFrame(repeat_summary))
show('完整 19 场景：旧新差异与存储往返变化分别汇总',pd.DataFrame(archive_summary))
show('旧捕获和当前运行中可核对的配置字段（只作为线索）',pd.DataFrame(config_rows),limit=35)
report_sections.append('## 读出重复性与历史捕获差异\n\n'+csv_markdown(pd.DataFrame(repeat_summary))+'\n\n'+
    csv_markdown(pd.DataFrame(archive_summary))+'\n\n统计单位为 19 个不同场景，不是 57 次重复。配置差异是排查线索，不自动证明因果。')

Read all nineteen historical readout comparisons for both models:  80%|########  | 8/10 [00:00<?, ?cell/s]

gemma12b：完整 19 场景的旧新读出差异

,scene_id,repeats,archived_readout,current_native_readout_mean,current_fp16_readout_mean,mean_absolute_archive_gap,maximum_absolute_archive_gap,mean_absolute_storage_shift,maximum_absolute_storage_shift,mean_absolute_residual_after_storage,maximum_absolute_residual_after_storage,archived_class,current_classes,any_class_changed_from_archive,within_current_repeat_class_changed
3,multi_e596431a55f8cd96,3,4.172300,6.494221,6.446305,2.321921,2.321921,0.047915,0.047915,2.274006,2.274006,left,left,False,False
15,single_lu3_ld1_ru1_rd4,3,-1.447117,0.845434,0.865493,2.292551,2.292551,0.020059,0.020059,2.312610,2.312610,right,left,True,False
1,multi_c0e457437617298d,3,-2.488817,-0.377130,-0.392168,2.111687,2.111687,0.015038,0.015038,2.096649,2.096649,right,balanced,True,False
2,multi_d6b66fc6f2ec3bae,3,-2.722634,-4.569774,-4.587048,1.847140,1.847140,0.017274,0.017274,1.864414,1.864414,right,right,False,False
0,multi_03b698958cd84596,3,-27.116551,-25.559859,-25.571416,1.556692,1.556692,0.011557,0.011557,1.545135,1.545135,right,right,False,False
13,single_lu3_ld1_ru1_rd2,3,1.342891,-0.193459,-0.176760,1.536350,1.536350,0.016699,0.016699,1.519651,1.519651,left,balanced,True,False
18,single_lu5_ld2_ru4_rd2,3,1.864812,3.309087,3.338619,1.444275,1.444275,0.029532,0.029532,1.473807,1.473807,left,left,False,False
10,single_lu2_ld2_ru2_rd2,3,-0.263878,1.058536,1.041018,1.322414,1.322414,0.017518,0.017518,1.304896,1.304896,balanced,left,True,False
6,single_lu1_ld3_ru3_rd1,3,0.258974,-0.955502,-0.959167,1.214477,1.214477,0.003664,0.003664,1.218141,1.218141,balanced,right,True,False
16,single_lu3_ld5_ru5_rd2,3,4.868052,6.017238,6.035189,1.149186,1.149186,0.017951,0.017951,1.167137,1.167137,left,left,False,False
5,single_lu1_ld2_ru2_rd4,3,-5.998412,-5.169542,-5.137751,0.828870,0.828870,0.031791,0.031791,0.860661,0.860661,right,right,False,False
12,single_lu2_ld5_ru3_rd4,3,-2.066334,-1.436075,-1.464655,0.630259,0.630259,0.028580,0.028580,0.601679,0.601679,right,right,False,False
14,single_lu3_ld1_ru1_rd3,3,0.119377,0.513625,0.529539,0.394248,0.394248,0.015914,0.015914,0.410162,0.410162,balanced,left,True,False
4,multi_f6b194290933e01e,3,-8.941403,-8.570580,-8.562757,0.370822,0.370822,0.007823,0.007823,0.378646,0.378646,right,right,False,False
9,single_lu1_ld4_ru4_rd2,3,-3.465768,-3.112071,-3.122017,0.353698,0.353698,0.009947,0.009947,0.343751,0.343751,right,right,False,False
11,single_lu2_ld2_ru3_rd5,3,-11.104943,-10.829257,-10.871138,0.275685,0.275685,0.041880,0.041880,0.233805,0.233805,right,right,False,False
8,single_lu1_ld4_ru3_rd1,3,1.391239,1.267324,1.267798,0.123915,0.123915,0.000474,0.000474,0.123441,0.123441,left,left,False,False
7,single_lu1_ld4_ru2_rd5,3,-6.716272,-6.770807,-6.792599,0.054535,0.054535,0.021792,0.021792,0.076327,0.076327,right,right,False,False
17,single_lu4_ld2_ru4_rd2,3,0.442974,0.429505,0.401250,0.013469,0.013469,0.028256,0.028256,0.041724,0.041724,balanced,balanced,False,False

qwen9b：完整 19 场景的旧新读出差异

,scene_id,repeats,archived_readout,current_native_readout_mean,current_fp16_readout_mean,mean_absolute_archive_gap,maximum_absolute_archive_gap,mean_absolute_storage_shift,maximum_absolute_storage_shift,mean_absolute_residual_after_storage,maximum_absolute_residual_after_storage,archived_class,current_classes,any_class_changed_from_archive,within_current_repeat_class_changed
12,single_lu2_ld5_ru3_rd4,3,-1.994012,2.792850,2.800655,4.786862,4.786862,0.007805,0.007805,4.794667,4.794667,right,left,True,False
2,multi_d6b66fc6f2ec3bae,3,-1.997707,1.089819,1.093174,3.087526,3.087526,0.003356,0.003356,3.090882,3.090882,right,left,True,False
0,multi_03b698958cd84596,3,-28.014347,-25.382525,-25.365719,2.631822,2.631822,0.016807,0.016807,2.648628,2.648628,right,right,False,False
4,multi_f6b194290933e01e,3,-8.989764,-6.675695,-6.724561,2.314069,2.314069,0.048866,0.048866,2.265203,2.265203,right,right,False,False
10,single_lu2_ld2_ru2_rd2,3,0.002109,2.302882,2.304686,2.300773,2.300773,0.001804,0.001804,2.302577,2.302577,balanced,left,True,False
18,single_lu5_ld2_ru4_rd2,3,1.985079,3.584017,3.577694,1.598938,1.598938,0.006323,0.006323,1.592615,1.592615,left,left,False,False
17,single_lu4_ld2_ru4_rd2,3,-0.006458,1.514627,1.505534,1.521086,1.521086,0.009093,0.009093,1.511993,1.511993,balanced,left,True,False
16,single_lu3_ld5_ru5_rd2,3,4.975885,6.390283,6.424258,1.414398,1.414398,0.033976,0.033976,1.448374,1.448374,left,left,False,False
13,single_lu3_ld1_ru1_rd2,3,0.994808,2.348220,2.342928,1.353412,1.353412,0.005292,0.005292,1.348120,1.348120,left,left,False,False
15,single_lu3_ld1_ru1_rd4,3,-1.000615,0.338771,0.384805,1.339386,1.339386,0.046035,0.046035,1.385420,1.385420,right,balanced,True,False
9,single_lu1_ld4_ru4_rd2,3,-3.992990,-2.903949,-2.911267,1.089041,1.089041,0.007318,0.007318,1.081723,1.081723,right,right,False,False
3,multi_e596431a55f8cd96,3,2.981841,4.028483,4.009651,1.046642,1.046642,0.018832,0.018832,1.027810,1.027810,left,left,False,False
6,single_lu1_ld3_ru3_rd1,3,0.005899,0.704335,0.715207,0.698436,0.698436,0.010872,0.010872,0.709308,0.709308,balanced,left,True,False
11,single_lu2_ld2_ru3_rd5,3,-10.969564,-10.510915,-10.499291,0.458649,0.458649,0.011623,0.011623,0.470273,0.470273,right,right,False,False
8,single_lu1_ld4_ru3_rd1,3,0.963423,0.582753,0.585931,0.380670,0.380670,0.003178,0.003178,0.377492,0.377492,left,left,False,False
1,multi_c0e457437617298d,3,-2.020667,-1.794490,-1.793668,0.226177,0.226177,0.000822,0.000822,0.226999,0.226999,right,right,False,False
7,single_lu1_ld4_ru2_rd5,3,-5.983981,-6.208163,-6.256579,0.224182,0.224182,0.048416,0.048416,0.272598,0.272598,right,right,False,False
5,single_lu1_ld2_ru2_rd4,3,-5.998769,-6.114920,-6.107886,0.116151,0.116151,0.007034,0.007034,0.109117,0.109117,right,right,False,False
14,single_lu3_ld1_ru1_rd3,3,0.013142,0.006107,0.005364,0.007035,0.007035,0.000743,0.000743,0.007778,0.007778,balanced,balanced,False,False

当前配置的重复性

      model  scenes  forwards  maximum_hidden_change  maximum_readout_change  maximum_centered_score_change  any_answer_changed  any_readout_class_changed
0  gemma12b      19       342                    0.0                     0.0                            0.0               False                      False
1    qwen9b      19       342                    0.0                     0.0                            0.0               False                      False

完整 19 场景：旧新差异与存储往返变化分别汇总

,model,scenes,repeat_rows,mean_absolute_archive_gap,maximum_absolute_archive_gap,mean_absolute_storage_shift,maximum_absolute_storage_shift,mean_absolute_residual_after_storage,class_changed_scenes,within_current_repeat_class_changed_scenes
0,gemma12b,19,57,1.044326,2.321921,0.020193,0.047915,1.044560,6,0
1,qwen9b,19,57,1.399750,4.786862,0.015168,0.048866,1.403767,6,0

旧捕获和当前运行中可核对的配置字段（只作为线索）

       model              source                     field                                                   value
0   gemma12b  historical_capture          activation_dtype                                               "float16"
1   gemma12b  historical_capture          capture_position  "final_token_after_generation_prompt_and_fixed_prefix"
2   gemma12b  historical_capture       decoder_layer_count                                                      48
3   gemma12b  historical_capture                     dtype                                              "bfloat16"
4   gemma12b  historical_capture             layer_indices                          [0, 7, 13, 20, 27, 34, 40, 47]
5   gemma12b  historical_capture                layer_path                           "model.language_model.layers"
6   gemma12b  historical_capture            schema_version                              "activation-discovery-1.0"
7   gemma12b      current_repeat  attention_implementation                                                  "sdpa"
8   gemma12b      current_repeat                batch_size                                                       1
9   gemma12b      current_repeat                      cuda                                                  "12.8"
10  gemma12b      current_repeat           cuda_capability                                                 [12, 0]
11  gemma12b      current_repeat                     dtype                                              "bfloat16"
12  gemma12b      current_repeat                       gpu          "NVIDIA RTX PRO 6000 Blackwell Server Edition"
13  gemma12b      current_repeat                layer_path                           "model.language_model.layers"
14  gemma12b      current_repeat                     torch                                          "2.11.0+cu128"
15  gemma12b      current_repeat              transformers                                                "5.14.0"
16    qwen9b  historical_capture          activation_dtype                                               "float16"
17    qwen9b  historical_capture          capture_position  "final_token_after_generation_prompt_and_fixed_prefix"
18    qwen9b  historical_capture       decoder_layer_count                                                      32
19    qwen9b  historical_capture                     dtype                                              "bfloat16"
20    qwen9b  historical_capture             layer_indices                           [0, 4, 9, 13, 18, 22, 27, 31]
21    qwen9b  historical_capture                layer_path                           "model.language_model.layers"
22    qwen9b  historical_capture            schema_version                              "activation-discovery-1.0"
23    qwen9b      current_repeat  attention_implementation                                                  "sdpa"
24    qwen9b      current_repeat                batch_size                                                       1
25    qwen9b      current_repeat                      cuda                                                  "12.8"
26    qwen9b      current_repeat           cuda_capability                                                 [12, 0]
27    qwen9b      current_repeat                     dtype                                              "bfloat16"
28    qwen9b      current_repeat                       gpu          "NVIDIA RTX PRO 6000 Blackwell Server Edition"
29    qwen9b      current_repeat                layer_path                           "model.language_model.layers"
30    qwen9b      current_repeat                     torch                                          "2.11.0+cu128"
31    qwen9b      current_repeat              transformers                                                "5.14.0"

In [11]:
%%cell_progress 10/10 Save a complete report and download one compact evidence package
import zipfile
from datetime import datetime,timezone
coverage_frame=pd.DataFrame(coverage)
export_csv('coverage.csv',coverage_frame)
export_json('input_manifest.json',dict(implementation=IMPLEMENTATION_SHA256,files=inputs))
all_inputs_unchanged=all(Path(p).is_file() and file_hash(p)==sha for p,sha in inputs.items())
assert all_inputs_unchanged,'核查过程中输入发生变化，请在原实验写入结束后重新运行本 CPU 核查。'
complete=bool(len(coverage_frame)==4 and coverage_frame.status.eq('validated_complete').all())
numeric_ok=bool(len(numeric_checks)==2 and all(r['all_primary_numbers_match'] for r in numeric_checks))
audit_fields_ok=bool(qwen_diagnosis.get('all_audit_fields_consistent',False))
status='complete' if complete and numeric_ok and audit_fields_ok else 'complete_with_items_to_resolve'
summary=dict(status=status,utc_time=datetime.now(timezone.utc).isoformat(),coverage=coverage,
    primary_statistics_reproduced=numeric_ok,qwen_technical_diagnosis=qwen_diagnosis,
    repeatability=repeat_summary,historical_readout=archive_summary,input_files_unchanged=all_inputs_unchanged,
    gpu_forward_count=0,original_scientific_decisions_unchanged=True)
export_json('AUDIT_COMPLETE.json',summary)
lines=['# 独立确认结果的补充核查','',
    '本次只读取已保存记录，没有运行模型，没有修改原样本、方向、剂量、容差或确认状态。','',
    '## 覆盖情况','',csv_markdown(coverage_frame),'',*report_sections,'',
    '## 使用范围','',
    '本报告区分单次写入匹配、跨前向实际幅度匹配与复位检查。技术失败、字段不一致和文件缺失分别保留。',
    '主结果重算使用原固定检验族；路径有效组与物理子组是事后描述，不是新的独立确认。',
    '先依据失败原因判断是否需要技术修正，再考虑是否需要重新采集。此 notebook 不自动启动 GPU 重跑。',
    '结果包包含完整失败明细、原 write_audits、家族物理配置、原完成状态、原主表和本次汇总。']
report_path=OUTPUT_ROOT/'REPORT_ZH.md';report_path.write_text('\n\n'.join(lines)+'\n',encoding='utf-8');export_files.add(report_path)
# Include only this run's registered outputs, never stale files from an earlier partial audit.
archive=OUTPUT_ROOT/'VisualTorque_Independent_Results_Audit_Output.zip'
temp=archive.with_suffix('.zip.tmp')
with zipfile.ZipFile(temp,'w',compression=zipfile.ZIP_DEFLATED) as bundle:
    for path in sorted(export_files):bundle.write(path,path.name)
temp.replace(archive)
show('最终覆盖状态',coverage_frame)
print(json.dumps(summary,ensure_ascii=False,indent=2))
print('报告：',report_path)
print('请带回这个结果包：',archive)
if AUTO_DOWNLOAD:
    try:
        from google.colab import files
        files.download(str(archive))
    except Exception as error:
        print('自动下载未触发，可从左侧 Files 或上述 Drive 路径手动下载：',type(error).__name__,str(error))

Save a complete report and download one compact evidence package:  90%|######### | 9/10 [00:00<?, ?cell/s]

最终覆盖状态

           stage     model              status                                                                           source issues
0        science   qwen27b  validated_complete  /content/drive/MyDrive/VisualTorque/results/cross_model_independent_confirma...
1        science  gemma12b  validated_complete  /content/drive/MyDrive/VisualTorque/results/cross_model_independent_confirma...
2  repeatability  gemma12b  validated_complete  /content/drive/MyDrive/VisualTorque/results/cross_model_independent_confirma...
3  repeatability    qwen9b  validated_complete  /content/drive/MyDrive/VisualTorque/results/cross_model_independent_confirma...

{
  "status": "complete",
  "utc_time": "2026-09-13T18:21:36.888132+00:00",
  "coverage": [
    {
      "stage": "science",
      "model": "qwen27b",
      "status": "validated_complete",
      "source": "/content/drive/MyDrive/VisualTorque/results/cross_model_independent_confirmation/qwen_three_path/main/Qwen__Qwen3.5-27B__373612cb",
      "issues": ""
    },
    {
      "stage": "science",
      "model": "gemma12b",
      "status": "validated_complete",
      "source": "/content/drive/MyDrive/VisualTorque/results/cross_model_independent_confirmation/gemma_l31_candidate/main/google__gemma-4-12B-it",
      "issues": ""
    },
    {
      "stage": "repeatability",
      "model": "gemma12b",
      "status": "validated_complete",
      "source": "/content/drive/MyDrive/VisualTorque/results/cross_model_independent_confirmation/readout_repeatability/main/google__gemma-4-12B-it",
      "issues": ""
    },
    {
      "stage": "repeatability",
      "model": "qwen9b",
      "status": "validated_complete",
      "source": "/content/drive/MyDrive/VisualTorque/results/cross_model_independent_confirmation/readout_repeatability/main/Qwen__Qwen3.5-9B",
      "issues": ""
    }
  ],
  "primary_statistics_reproduced": true,
  "qwen_technical_diagnosis": {
    "status": "diagnosed_from_saved_records",
    "ua_equal": {
      "attempted": 2048,
      "failed": 0,
      "affected_families": 0,
      "local_match_failures": 0,
      "cross_match_failures": 0,
      "inconsistent_audits": 0
    },
    "ub_equal": {
      "attempted": 2048,
      "failed": 1,
      "affected_families": 1,
      "local_match_failures": 1,
      "cross_match_failures": 1,
      "inconsistent_audits": 0
    },
    "ab_equal": {
      "attempted": 2048,
      "failed": 0,
      "affected_families": 0,
      "local_match_failures": 0,
      "cross_match_failures": 0,
      "inconsistent_audits": 0
    },
    "all_original_failed_records": 1,
    "all_affected_families": 1,
    "all_audit_fields_consistent": true,
    "originally_fully_valid_families": 63,
    "original_decision": {
      "accuracy_change": {
        "repair_confirmed": {
          "u": true,
          "a": true
        },
        "selective_dependence_confirmed": {
          "ua": true,
          "ub": false,
          "ab": true
        }
      },
      "margin_change": {
        "repair_confirmed": {
          "u": true,
          "a": true
        },
        "selective_dependence_confirmed": {
          "ua": true,
          "ub": false,
          "ab": true
        }
      }
    }
  },
  "repeatability": [
    {
      "model": "gemma12b",
      "scenes": 19,
      "forwards": 342,
      "maximum_hidden_change": 0.0,
      "maximum_readout_change": 0.0,
      "maximum_centered_score_change": 0.0,
      "any_answer_changed": false,
      "any_readout_class_changed": false
    },
    {
      "model": "qwen9b",
      "scenes": 19,
      "forwards": 342,
      "maximum_hidden_change": 0.0,
      "maximum_readout_change": 0.0,
      "maximum_centered_score_change": 0.0,
      "any_answer_changed": false,
      "any_readout_class_changed": false
    }
  ],
  "historical_readout": [
    {
      "model": "gemma12b",
      "scenes": 19,
      "repeat_rows": 57,
      "mean_absolute_archive_gap": 1.0443259815036254,
      "maximum_absolute_archive_gap": 2.3219209441936206,
      "mean_absolute_storage_shift": 0.020192943570373108,
      "maximum_absolute_storage_shift": 0.0479154399979853,
      "mean_absolute_residual_after_storage": 1.0445600599889302,
      "class_changed_scenes": 6,
      "within_current_repeat_class_changed_scenes": 0
    },
    {
      "model": "qwen9b",
      "scenes": 19,
      "repeat_rows": 57,
      "mean_absolute_archive_gap": 1.3997502380219717,
      "maximum_absolute_archive_gap": 4.786861898222485,
      "mean_absolute_storage_shift": 0.015168214664100095,
      "maximum_absolute_storage_shift": 0.0488661461944346,
      "mean_absolute_residual_after_storage": 1.4037672303887134,
      "class_changed_scenes": 6,
      "within_current_repeat_class_changed_scenes": 0
    }
  ],
  "input_files_unchanged": true,
  "gpu_forward_count": 0,
  "original_scientific_decisions_unchanged": true
}
报告： /content/drive/MyDrive/VisualTorque/results/cross_model_independent_confirmation/completion_audit/main/REPORT_ZH.md
请带回这个结果包： /content/drive/MyDrive/VisualTorque/results/cross_model_independent_confirmation/completion_audit/main/VisualTorque_Independent_Results_Audit_Output.zip