# 固定位置的新家族确认

默认 Gemma；三个模型各跑一次。

[实验设置与运行说明](../../../docs/experiment_notes/05_appendix_content_and_encoding/fe81978907b6d37f.md)

In [ ]:
# Notebook utilities: support/visualtorque_checks.py
import base64 as _vt_base64, gzip as _vt_gzip, sys as _vt_sys, types as _vt_types
_vt_source = _vt_gzip.decompress(_vt_base64.b64decode("H4sIAAAAAAACCo1Y647bthL+76dgtziwtLGVTZAGqFs3J8BJkABJESCLoqjXFWiJsnmWElWS2qx7Afo0fbA+SWd4kSnJ23Z/JBLnPvPNcOSLi4vXXDBSHFhxqwltStJIw3ZS3pKS61bQI+kMF9xwpjPyrSS1LJkgUhF23zLFa9YYUrKWNSVrCmS6uLiY8bqVypCqawojpdDh4ED1QfBdeFUsPOmjnlVK1uRgapG1VGmmiKe9uX7/7oM9cSwtNagkkD/A62w2K1lFKgglRxsJ8qSrGYG/ku+ZNmQdjGf6QJ9+8TxJLfUTNwerwolkEiJJ5mo3TwnVINKUgjk9+FdB3MWha24Jbwg3TCWC1ruSrjxnphgtkydXT5+RS4L/pQuym8/Tk4aTR1nXltSwxOpzzihmOtUE+oHduydw1cXnPM8xzDhCLzZ35NWcPBpnYiqf7455Q2uW2JepstjUiQX0AAFyGZFnljw9diZ3R8M0UhMIlj7s8Kg4lvlMBhqpair4z9ZgckdFx0Z+G+WPoRa1vGOtYhW/T3pbqCl/8/LjG3BXsayQdYsxqnny4uvPNi+XP9Dlz1fLL/NtmrxYbeCJLquXy9fbX54/++3X+P3Z1W/AMhQB7fn1q++v8/dv37/6CBaSuWH35jH0EW/mC+LeEOP9S03VbSk/NfMQInpEC5MjNcF/FjY5TK+/lU2IFprs4wHQz5rQpqz0bAsiW8NlQ4U4klvGWt7sCYVY75jSfAfNLqC7u9Y2qoUjGFUMdBQsqakpDhFcbSohDnue7ZXsWt84+KfRBaBars3qydUWKjn/8/c/sKLucPl8te35eeV9JFzjnCEY0bA3eOW1QoN5XhxK7nFjSVvymTc5FI1QYKkD4lDBesTRgx6oMZosUDLd7RKfoAXBimCpCkG1Jvl33Ob0Got1GlRh9EBm85w33OR5opmonHgoaJRn3cEwTdKs5y5kA/UyeXGgChCs16+p0CxKPWjLnDL7GGpvX0CogbaBMGNzC7LZDuVlVWlmkG9zdZ6UgTyM9qTO8N/UDsAaawOtU/GmtDNwfoPYtokZOSiQTgUYwErP+qS4aZlrQ5UxdB9yQ/cLQo1RcWYAEHCOJqGHC8Vbg62jzVGw8VwdmQSxiUWIYmBvami9Huj5Wwtng8LR5Q1EIy9g+0HVDnH9kSthCUYG8wA1DiqextqDEPQHMg4NCN4AfAspurohPsg9M63UUUfbILEqgcPjYIPSZEmeYIc7HdPEeNhltMV1IEmsooXX94gIuFltRhbB0XQ883Ay/t3Me8foHbMQ4bvOIKTBr1uEvUUGPiAw3MzgNd0zmwhAjwH1/cTz+8V62L6D1oz4soqxMnF9H50WQmrmU4dt4aOFyBd+bNo2wakL4kHIpSgCBer1jbpZWR3bMDzhf3sMKv0Q9WMJT0eZC9fIg9n7nLyDVAFQteENxQtCg7oa7iXSaQo5WIC/hehKvC5sVomRVs8S94SSgGe8AlM6C1mwkwMGAdw/3OANerO9STY/ptvLm/TXgzGtfrF6/Hjz443++pvtozTMiMEKMM/+L3mD6TGIYE7+Q54SBqNuiPvW5nYM+egPK8AXxOlpoApdDT1mmJXUE6DZ/LpFYUFq2GLXw4t6mj+7y0LWoo5EtKLTKI9zI7rdhyGE4kyZ+9t/GvPMNzUgtAFcNEXvr+DaRAj6nDS7CvciQ+ASqTmUhZK6E7i2Q9PCRoQlhWLu8EUqrCV2CFRU0WPW68FC2IkTiuL2qOiS1KAU6CEViZOY1sUX1wk4eKArOsF1BNCs19cKNGN0XilMLG/e5uF0O3tVvUmfAm/xfH4g4jTWM+oUKICfo9Mq9zGWvHDT9tTgtnKArWjDG8z2QHc6xtMdzzbIso0Q5GAYEx0ahykdpPO0evzPLX4fDXx01M5cfsd1RwUU+acOr1ekgDnM9uyhjcRxxbsIzvKTsHs4iX9ScH1F28wDkpnjm2yz6QQmeC/4rWpgw0HGGbLP6fBDzKIb8m1pZ+5p5wBSI82V6OCjCOmRtrD+xe47xjROG9yWePX0mcO5ONXiuZJYm+f1SMxhoYNiHjxRJ5dU7eHuury8/YRPYeJAjCjmdx9Tys7vPiVTKl5++lr1to86mIyXD8cW7d7hg/8k6N2dn0MSGHdb6DjZI6OLETa91n4I4/chbEC5/3JJYP4xBcBn5iDL3GmAPHT424K3JRXfw7UlohjPSdlODoOzl4GAbbCQz17Y0yaRep/OhOoXNPv+3/6XDUAZbXWvL+3h0nY7mNOHB2rrXcSTYTLxBL8bB9MKD2FDh8XJats8WW1PhYU+qfp0IVacoaFadxbmmnflDMcmKIqnlPVhTJ+0cUjBJGKXMp+P7Gy6w4yK4XSuvl5JAJId/EL0QIKRKcRoZXxtsTb9VUs24viVuyDAWfzFwm2NxYGLctkqWTAYskJC1sDIEW4gIfoF0n6lgq0ArWidU8dh5u1PVm8/HCGKJvxkBSjMeWuPTmW8L1hryFvL8Uopqc59HzhURh/g6MQ6Vpik/+DhRNFkHDkN4y616jL/lkMloHd8PXAq4V05/xeSBygCsNvhnLu1xX4yoY7wChid92EMxhNqemA65aj5TN8667CHN7C6KraH5Qm/WVvFctU1eQFUkBonIR3JP2gxhq5PrX3/C0ov0eJaFQAA"))
_vt_checks = _vt_types.ModuleType("visualtorque_checks")
exec(compile(_vt_source, "<visualtorque_checks>", "exec"), _vt_checks.__dict__)
_vt_sys.modules["visualtorque_checks"] = _vt_checks
_vt_checks.install_display()
del _vt_source

In [1]:
# Run once. Every later code cell reports both cell and inner-loop progress.
import re
import threading
import time
from IPython.core.magic import register_cell_magic
from tqdm.auto import tqdm

_SETUP_PROGRESS = tqdm(total=1, desc='Initialize progress display', unit='cell')
_ACTIVE_CELL_PROGRESS = None

def cell_stage(message):
    if _ACTIVE_CELL_PROGRESS is not None:
        _ACTIVE_CELL_PROGRESS['stage'] = str(message)
        elapsed = time.monotonic() - _ACTIVE_CELL_PROGRESS['started']
        _ACTIVE_CELL_PROGRESS['bar'].set_postfix_str(
            f"{message} | elapsed {elapsed:.0f}s", refresh=True
        )

@register_cell_magic
def cell_progress(line, cell):
    global _ACTIVE_CELL_PROGRESS
    specification = line.strip() or 'Cell progress'
    match = re.fullmatch(r'(\d+)/(\d+)\s+(.+)', specification)
    if match:
        current, total, label = int(match.group(1)), int(match.group(2)), match.group(3)
        initial = current - 1
    else:
        current, total, label, initial = 1, 1, specification, 0
    started = time.monotonic()
    bar = tqdm(
        total=total, initial=initial, desc=label, unit='cell',
        dynamic_ncols=True, leave=True,
    )
    state = {'bar': bar, 'started': started, 'stage': 'starting'}
    _ACTIVE_CELL_PROGRESS = state
    stopped = threading.Event()

    def heartbeat():
        while not stopped.wait(1.0):
            elapsed = time.monotonic() - started
            bar.set_postfix_str(
                f"{state['stage']} | elapsed {elapsed:.0f}s", refresh=True
            )

    worker = threading.Thread(target=heartbeat, daemon=True)
    worker.start()
    succeeded = False
    try:
        cell_stage('running')
        result = get_ipython().run_cell(cell)
        result.raise_error()
        succeeded = True
        return result.result
    finally:
        stopped.set()
        worker.join(timeout=2.0)
        elapsed = time.monotonic() - started
        if succeeded:
            bar.n = current
            bar.set_postfix_str(f"complete | elapsed {elapsed:.0f}s", refresh=True)
        else:
            bar.set_postfix_str(f"failed | elapsed {elapsed:.0f}s", refresh=True)
        bar.close()
        _ACTIVE_CELL_PROGRESS = None

_SETUP_PROGRESS.update(1)
_SETUP_PROGRESS.close()
print('Cell progress helper ready: 17 tracked cells.')

IMPLEMENTATION_SHA256 = '160372af558929c42134517d3ffc09527278d018135dd39a46f32eb6987dde7d'
IMPLEMENTATION_SHA256 = '6631da39a2e1a6c885408e1d338df998a82bde9be59bd7b692df54d2a0b3708f'

Initialize progress display:   0%|          | 0/1 [00:00<?, ?cell/s]

Cell progress helper ready: 17 tracked cells.

In [2]:
%%cell_progress 1/15 Mount Drive
cell_stage('Mounting Google Drive')
from google.colab import drive
drive.mount('/content/drive')

cell_stage('Locating VisualTorque project')
from pathlib import Path
PROJECT_CANDIDATES = (
    Path('/content/drive/MyDrive/VisualTorque'),
    Path('/content/drive/MyDrive/VisualTorque/VisualTorque'),
)
PROJECT_ROOT = next(
    (
        path for path in PROJECT_CANDIDATES
        if (path / 'toolkit' / 'pyproject.toml').is_file()
    ),
    None,
)
assert PROJECT_ROOT is not None, (
    'Could not find VisualTorque/toolkit/pyproject.toml on Drive.'
)
TOOLKIT_ROOT = PROJECT_ROOT / 'toolkit'
print('Project:', PROJECT_ROOT)

Mount Drive:   0%|          | 0/15 [00:00<?, ?cell/s]

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Project: /content/drive/MyDrive/VisualTorque

In [3]:
%%cell_progress 2/15 Install inference environment
import importlib
import os

os.environ.setdefault('PYTORCH_CUDA_ALLOC_CONF', 'expandable_segments:True')
import subprocess
import sys

cell_stage('Removing unused TorchAudio')
subprocess.run(
    [sys.executable, '-m', 'pip', 'uninstall', '-y', 'torchaudio'],
    check=False,
)
cell_stage('Installing pinned inference and analysis dependencies')
subprocess.check_call([
    sys.executable, '-m', 'pip', 'install', '-q', '-U',
    'transformers==5.14.0', 'accelerate>=1.10', 'sentencepiece',
    'protobuf', 'huggingface_hub>=0.34', 'hf_xet>=1.1', 'tqdm>=4.66',
    'pandas>=2.2', 'matplotlib>=3.8', 'scikit-learn>=1.5',
])

cell_stage('Registering the live VisualTorque source tree')
SRC_ROOT = TOOLKIT_ROOT / 'src'
PACKAGE_ROOT = SRC_ROOT / 'visual_torque_toolkit'
assert (PACKAGE_ROOT / '__init__.py').is_file(), PACKAGE_ROOT
source_text = str(SRC_ROOT)
sys.path[:] = [entry for entry in sys.path if entry != source_text]
sys.path.insert(0, source_text)
for module_name in tuple(sys.modules):
    if (
        module_name == 'visual_torque_toolkit'
        or module_name.startswith('visual_torque_toolkit.')
    ):
        del sys.modules[module_name]
importlib.invalidate_caches()

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torchvision
import visual_torque_toolkit
from IPython.display import display
from transformers import AutoModelForMultimodalLM, AutoProcessor
from visual_torque_toolkit.behavior.adapter import HuggingFaceMultimodalAdapter

required_features = (
    '_template', '_to_device', '_candidate_plan', '_append_text_prefix',
)
assert all(
    hasattr(HuggingFaceMultimodalAdapter, name)
    for name in required_features
)
toolkit_path = Path(visual_torque_toolkit.__file__).resolve()
assert PACKAGE_ROOT.resolve() in toolkit_path.parents, toolkit_path
print('torch:', torch.__version__, '| CUDA:', torch.version.cuda)
print('torchvision:', torchvision.__version__)
print('Toolkit source:', toolkit_path)

Install inference environment:   7%|6         | 1/15 [00:00<?, ?cell/s]

torch: 2.11.0+cu128 | CUDA: 12.8
torchvision: 0.26.0+cu128
Toolkit source: /content/drive/MyDrive/VisualTorque/toolkit/src/visual_torque_toolkit/__init__.py

In [4]:
%%cell_progress 3/15 Check GPU access
cell_stage('Checking CUDA device')
assert torch.cuda.is_available(), 'Select an A100 GPU runtime.'
print(torch.cuda.get_device_name(0))
print('CUDA memory (GB):', round(
    torch.cuda.get_device_properties(0).total_memory / 2**30, 1
))

cell_stage('Authenticating with Hugging Face')
from google.colab import userdata
from huggingface_hub import login
try:
    token = userdata.get('HF_TOKEN')
    if token:
        login(token=token, add_to_git_credential=False)
        print('Hugging Face login complete.')
    else:
        print('HF_TOKEN is not set. Public checkpoints may still work.')
except Exception as exc:
    print('Hugging Face login skipped:', exc)

Check GPU access:  13%|#3        | 2/15 [00:00<?, ?cell/s]

NVIDIA RTX PRO 6000 Blackwell Server Edition
CUDA memory (GB): 95.0
Hugging Face login skipped: Secret HF_TOKEN does not exist.

In [5]:
%%cell_progress 4/15 Load shared validation utilities
"""Pure CPU utilities embedded in the follow-up notebooks; no model execution."""
import hashlib
import json
from pathlib import Path
from collections import defaultdict, Counter
from itertools import combinations, product
import numpy as np
import pandas as pd


def plain(value):
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, np.generic):
        return value.item()
    raise TypeError(type(value).__name__)


def digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, default=plain, allow_nan=False).encode()).hexdigest()


from visualtorque_checks import file_hash


def read_json(path):
    return json.loads(Path(path).read_text(encoding='utf-8'))


def read_jsonl(path):
    return [json.loads(s) for s in Path(path).read_text(encoding='utf-8').splitlines() if s.strip()]


def save_json(path, value):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_suffix(path.suffix + '.tmp')
    temp.write_text(json.dumps(value, ensure_ascii=False, indent=2, default=plain, allow_nan=False) + '\n', encoding='utf-8')
    temp.replace(path)


def freeze(path, identity):
    identity = json.loads(json.dumps(identity, default=plain, sort_keys=True, allow_nan=False))
    if Path(path).is_file():
        assert read_json(path) == identity, f'Configuration changed; preserve the old run and use a new RUN_ID: {path}'
    else:
        save_json(path, identity)
    return digest(identity)


def cached_json(directory, key, identity, compute):
    path = Path(directory) / (digest(str(key))[:24] + '.json')
    expected = digest(identity)
    if path.is_file():
        old = read_json(path)
        assert old['key'] == str(key) and old['identity'] == expected, f'Incompatible cache: {path}'
        return old['result']
    value = compute()
    save_json(path, dict(key=str(key), identity=expected, result=value))
    return value


def bootstrap(values, key='', replicates=10000):
    x = np.asarray(values, dtype=float)
    assert x.ndim == 1 and len(x) and np.isfinite(x).all()
    rng = np.random.default_rng(int(digest(str(key))[:16], 16))
    draws = np.concatenate([rng.choice(x, (min(250, replicates-i), len(x)), replace=True).mean(1)
                            for i in range(0, replicates, 250)])
    return dict(n=len(x), mean=float(x.mean()), lower=float(np.quantile(draws, .025)),
                upper=float(np.quantile(draws, .975)),
                p_value=float((1 + (draws <= 0).sum()) / (replicates + 1)))


def bh(values):
    p = np.asarray(values, dtype=float)
    assert np.isfinite(p).all() and ((p >= 0) & (p <= 1)).all()
    order = np.argsort(p)
    q = np.empty_like(p)
    previous = 1.
    for rank in range(len(p)-1, -1, -1):
        i = order[rank]
        previous = min(previous, p[i]*len(p)/(rank+1))
        q[i] = previous
    return q


def paired(left, right, id_col, value):
    assert left[id_col].is_unique and right[id_col].is_unique
    assert set(left[id_col]) == set(right[id_col]), 'Different paired support'
    out = left[[id_col, value]].merge(right[[id_col, value]], on=id_col, validate='one_to_one', suffixes=('_l', '_r'))
    return out[value+'_l'].to_numpy(float) - out[value+'_r'].to_numpy(float)


def semantic_scores(record):
    if 'semantic_logprobs' in record:
        return {str(k): float(v) for k, v in record['semantic_logprobs'].items()}
    values = record['candidate_logprobs']
    if isinstance(values, dict):
        return {str(record['label_to_semantic'][k]): float(v) for k, v in values.items()}
    return dict(zip(map(str, record['candidate_semantics']), map(float, values)))


def correct_margin(record):
    values = semantic_scores(record)
    gold = str(record['gold_semantic'])
    assert gold in values and len(values) >= 2
    return values[gold] - max(v for k, v in values.items() if k != gold)


def random_unit(shape, key):
    r = np.random.default_rng(int(digest(key)[:16], 16)).normal(size=shape)
    return r / np.linalg.norm(r)


def coordinate_clamp(pre, untreated, axis, cast):
    h, base, u = [np.asarray(x, dtype=np.float64) for x in (pre, untreated, axis)]
    u = u / np.linalg.norm(u)
    a = float(np.sum((h-base)*u))
    return np.asarray(cast(h-a*u), dtype=np.float64), a


def native_norm_edit(pre, direction, norm, cast, tolerance=.02, steps=48):
    h = np.asarray(pre, dtype=np.float64)
    r = np.asarray(direction, dtype=np.float64)
    assert np.isfinite(h).all() and np.isfinite(r).all() and norm >= 0 and np.linalg.norm(r) > 0
    r /= np.linalg.norm(r)
    if norm == 0:
        return h.copy(), dict(actual_norm=0., target_norm=0., relative_error=0., matched=True)
    lo, hi = 0., max(float(norm), 1e-12)
    for _ in range(32):
        if np.linalg.norm(np.asarray(cast(h+hi*r))-h) >= norm:
            break
        hi *= 2
    best, error = h.copy(), 1.
    for _ in range(steps):
        mid = (lo+hi)/2
        candidate = np.asarray(cast(h+mid*r), dtype=np.float64)
        actual = float(np.linalg.norm(candidate-h))
        current = abs(actual-norm)/norm
        if current < error:
            best, error = candidate.copy(), current
        if error <= tolerance:
            break
        if actual < norm:
            lo = mid
        else:
            hi = mid
    return best, dict(actual_norm=float(np.linalg.norm(best-h)), target_norm=float(norm),
                      relative_error=float(error), matched=bool(error <= tolerance))


def equal_removal(pre, untreated, axis, random_direction, cast, tolerance=.02):
    target, coefficient = coordinate_clamp(pre, untreated, axis, cast)
    target_norm = float(np.linalg.norm(target-np.asarray(pre)))
    sign = 1. if coefficient >= 0 else -1.
    post, audit = native_norm_edit(pre, -sign*np.asarray(random_direction), target_norm, cast, tolerance)
    audit.update(reference_coefficient=coefficient, reference_actual_norm=target_norm)
    return post, audit


def geometry_signature(stacks):
    a = tuple(sorted((str(s['side']), int(s['distance']), int(s['units'])) for s in stacks))
    b = tuple(sorted(('right' if side == 'left' else 'left', d, u) for side, d, u in a))
    return min(a, b)  # mirrors belong to the same physical family


def geometries_in(value):
    found = set()
    if isinstance(value, dict):
        stacks = value.get('stacks')
        if isinstance(stacks, list) and stacks and all(isinstance(s, dict) and {'side','distance','units'} <= set(s) for s in stacks):
            found.add(geometry_signature(stacks))
        # Some prior matched cohorts store geometry instead of stack records.
        geom = value.get('pair_geometry')
        if isinstance(geom, (list, tuple)) and len(geom) == 4 and all(isinstance(x, (int,float)) for x in geom):
            u1,d1,u2,d2 = map(int, geom)
            found.add(geometry_signature([dict(side='left',distance=d1,units=u1),dict(side='right',distance=d2,units=u2)]))
        if isinstance(geom, (list, tuple)) and len(geom)==2 and all(isinstance(x,(list,tuple)) and len(x)==2 for x in geom):
            (u1,d1),(u2,d2)=geom
            found.add(geometry_signature([dict(side='left',distance=int(d1),units=int(u1)),dict(side='right',distance=int(d2),units=int(u2))]))
        for child in value.values():
            found.update(geometries_in(child))
    elif isinstance(value, list):
        for child in value:
            found.update(geometries_in(child))
    return found


def physics(stacks):
    units = {s:sum(int(x['units']) for x in stacks if x['side']==s) for s in ('left','right')}
    dist = {s:sum(int(x['distance']) for x in stacks if x['side']==s) for s in ('left','right')}
    torque = {s:sum(int(x['units'])*int(x['distance']) for x in stacks if x['side']==s) for s in ('left','right')}
    out = lambda x:'left' if x>0 else 'right' if x<0 else 'balanced'
    net=torque['left']-torque['right']; w=units['left']-units['right']; d=dist['left']-dist['right']
    return dict(net_torque=net,outcome=out(net),weight_score=w,distance_score=d,
                normalized_margin=abs(net)/max(1,sum(torque.values())),
                left_units=units['left'],right_units=units['right'],left_torque=torque['left'],right_torque=torque['right'],
                strategy_predictions=dict(exact_torque=out(net),weight_only=out(w),distance_only=out(d)))


def exclusion_snapshot(project, followup_root, dataset_dir=None):
    lock=Path(followup_root)/'prior_geometry_snapshot.json'
    if lock.is_file():
        old=read_json(lock)
        for path, sha in old['files'].items():
            assert file_hash(Path(path))==sha, f'Prior input changed: {path}'
        return {tuple(tuple(x) for x in sig) for sig in old['signatures']}, old
    paths={Path(dataset_dir or project/'data/dataset_v1')/'scenes.jsonl'}
    for pattern in ('*manifest*.jsonl','*support*.jsonl','*geometries*.jsonl'):
        paths.update(p for p in (project/'results').rglob(pattern) if Path(followup_root) not in p.parents)
    excluded=set(); hashes={}
    for path in sorted(paths):
        assert path.is_file(), f'Missing required geometry input: {path}'
        excluded.update(geometries_in(read_jsonl(path)))
        hashes[str(path.resolve())]=file_hash(path)
    assert excluded, 'No prior physical geometry was indexed'
    old=dict(files=hashes,signatures=sorted(excluded),mirror_canonical=True)
    save_json(lock,old)
    return excluded,old


def inverse_families(n, seed, excluded):
    assert n%4==0
    pool=defaultdict(list)
    for dl in combinations(range(1,7),2):
        for dr in combinations(range(1,7),2):
            for units in product(range(1,6), repeat=4):
                stacks=[dict(side=side,distance=d,units=u) for side,d,u in zip(('left','left','right','right'),dl+dr,units)]
                f=physics(stacks)
                pool[dl+dr].append((stacks,f))
    candidates=[]
    for distances,rows in pool.items():
        by_net=defaultdict(list)
        for stacks,f in rows:
            if f['outcome']==f['strategy_predictions']['weight_only'] and f['outcome']!='balanced':
                by_net[f['net_torque']].append((stacks,f))
        for stacks,f in rows:
            margin=f['normalized_margin']; difficulty='hard' if .08<=margin<.22 else 'moderate' if .22<=margin<.45 else None
            if (difficulty and f['outcome']!='balanced' and f['strategy_predictions']['weight_only'] not in ('balanced',f['outcome'])
                    and f['strategy_predictions']['distance_only']==f['outcome'] and abs(f['distance_score'])>=2):
                sources=by_net.get(f['net_torque'],[])
                if sources:candidates.append((digest([seed,stacks]),difficulty,stacks,f,sources))
    candidates.sort(key=lambda r:r[0]); used=set(excluded); counts=Counter(); result=[]
    for _,difficulty,stacks,f,sources in candidates:
        stratum=(difficulty,f['outcome'])
        if counts[stratum]>=n//4 or geometry_signature(stacks) in used:continue
        valid=[(s,g) for s,g in sources if geometry_signature(s) not in used|{geometry_signature(stacks)}]
        if not valid:continue
        valid.sort(key=lambda x:(sum(abs(a['units']-b['units']) for a,b in zip(stacks,x[0])),digest([seed,x[0]])))
        src,sf=valid[0];fid='fixed_'+digest([seed,stacks,src])[:20]
        roles={name:dict(scene_id=fid+'__'+name,image_filename=fid+'__'+name+'.png',stacks=s,features=g)
               for name,s,g in [('base',stacks,f),('aligned_source',src,sf)]}
        result.append(dict(family_id=fid,remapping_split='new_fixed_confirmation',roles=roles,margin_bin=difficulty))
        used.update([geometry_signature(stacks),geometry_signature(src)]);counts[stratum]+=1
        if len(result)==n:break
    assert len(result)==n and set(counts.values())=={n//4}, (len(result),counts)
    return sorted(result,key=lambda r:r['family_id'])


def repair_families(n, seed, excluded):
    assert n%4==0
    candidates=defaultdict(list)
    for ul,dl,ur,dr in product(range(1,9),range(1,7),range(1,9),range(1,7)):
        s=[dict(side='left',units=ul,distance=dl),dict(side='right',units=ur,distance=dr)]
        f=physics(s)
        if f['net_torque']==0:continue
        if ul==ur and dl!=dr:kind='equal_weight_distance'
        elif f['strategy_predictions']['weight_only'] not in ('balanced',f['outcome']):kind='weight_distance_conflict'
        elif f['strategy_predictions']['weight_only']==f['outcome'] and f['strategy_predictions']['distance_only']==f['outcome']:kind='aligned_cues'
        else:continue
        candidates[kind].append(s)
    for units in product(range(1,6),repeat=4):
        for distances in [((1,3),(2,5)),((2,5),(1,4)),((1,6),(3,5)),((2,4),(3,6))]:
            s=[dict(side=side,distance=d,units=u) for side,d,u in zip(('left','left','right','right'),distances[0]+distances[1],units)]
            if physics(s)['net_torque']!=0:candidates['multi_stack_sum'].append(s)
    used=set(excluded); result=[]
    for kind in ('equal_weight_distance','weight_distance_conflict','multi_stack_sum','aligned_cues'):
        rows=sorted(candidates[kind],key=lambda s:digest([seed,kind,s])); count=0
        for stacks in rows:
            sig=geometry_signature(stacks)
            if sig in used:continue
            fid='repair_'+digest([seed,kind,sig])[:20];scenes=[]
            for mirror in (False,True):
                current=[dict(s,side=('right' if s['side']=='left' else 'left')) if mirror else dict(s) for s in stacks]
                for style in ('standard','alternate'):
                    sid=f'{fid}__m{int(mirror)}__{style}'
                    scenes.append(dict(scene_id=sid,image_filename=sid+'.png',stacks=current,features=physics(current),style=style,mirror=mirror))
            result.append(dict(family_id=fid,stratum=kind,scenes=scenes));used.add(sig);count+=1
            if count==n//4:break
        assert count==n//4,(kind,count,'Insufficient unused geometries; do not silently change task ranges')
    return sorted(result,key=lambda r:r['family_id'])

Load shared validation utilities:  20%|##        | 3/15 [00:00<?, ?cell/s]

In [6]:
%%cell_progress 5/15 Prepare existing Dataset v1
cell_stage('Checking local and Drive dataset caches')
from zipfile import ZipFile

REQUIRED_DATASET_FILES = {
    'dataset_config.json', 'scenes.jsonl', 'counterfactual_pairs.jsonl',
    'questions.jsonl', 'splits.json', 'statistics.json',
}
DATASET_DIR = Path('/content/visualtorque_dataset_v1')
DATASET_ARCHIVE = PROJECT_ROOT / 'data' / 'dataset_v1.zip'
LEGACY_DATASET_DIR = PROJECT_ROOT / 'data' / 'dataset_v1'

def dataset_complete(path):
    return path.is_dir() and all(
        (path / name).is_file() for name in REQUIRED_DATASET_FILES
    )

if not dataset_complete(DATASET_DIR):
    DATASET_DIR.mkdir(parents=True, exist_ok=True)
    if DATASET_ARCHIVE.is_file():
        cell_stage('Extracting Dataset v1 archive')
        with ZipFile(DATASET_ARCHIVE, 'r') as bundle:
            members = [m for m in bundle.infolist() if not m.is_dir()]
            root = DATASET_DIR.resolve()
            for member in tqdm(members, desc='Extracting Dataset v1', unit='file'):
                target = (DATASET_DIR / member.filename).resolve()
                if root not in target.parents:
                    raise ValueError(f'Unsafe archive path: {member.filename}')
                bundle.extract(member, DATASET_DIR)
    elif dataset_complete(LEGACY_DATASET_DIR):
        DATASET_DIR = LEGACY_DATASET_DIR
    else:
        raise FileNotFoundError(
            'Run the Dataset v1 build/cache cell in the behavior notebook first.'
        )
assert dataset_complete(DATASET_DIR)
print('Dataset:', DATASET_DIR)

Prepare existing Dataset v1:  27%|##6       | 4/15 [00:00<?, ?cell/s]

Dataset: /content/visualtorque_dataset_v1

In [7]:
%%cell_progress 6/15 Freeze fixed-site protocol

import math,hashlib,json
from datetime import datetime,timezone
RUN_ID='main'
MODEL_KEY='qwen9b'  # qwen9b / gemma12b / qwen27b; use a fresh runtime per model
MODEL_SPECS={
 'qwen9b':dict(model_id='Qwen/Qwen3.5-9B',model_slug='Qwen__Qwen3.5-9B',expected_layers=32,
    revision='c202236235762e1c871ad0ccb60c8ee5ba337b9a',scan_layers=(31,),endpoint_layer=31,repair_layer=31,candidate_layers=(12,16,20,24,27,29)),
 'gemma12b':dict(model_id='google/gemma-4-12B-it',model_slug='google__gemma-4-12B-it',expected_layers=48,
    revision='707f0a3b8a3c7ad586ed01e27eafbad8a27dd0f7',scan_layers=(37,47),endpoint_layer=47,repair_layer=47,candidate_layers=(19,25,31,37,41,44)),
 'qwen27b':dict(model_id='Qwen/Qwen3.5-27B',model_slug='Qwen__Qwen3.5-27B__373612cb',expected_layers=64,
    revision='373612cb4f9288fcf550b526d86d85febedd9801',scan_layers=(49,63),endpoint_layer=63,repair_layer=55,candidate_layers=(25,33,41,49)),
}
assert MODEL_KEY in MODEL_SPECS
SPEC=MODEL_SPECS[MODEL_KEY];MODEL_ID=SPEC['model_id'];MODEL_REVISION=SPEC['revision'];MODEL_SLUG=SPEC['model_slug']
EXPECTED_LAYER_COUNT=SPEC['expected_layers'];MODEL_DTYPE='bfloat16';DEVICE_MAP='auto'
FOLLOWUP_ROOT=PROJECT_ROOT/'results/cross_model_followup_v1';FOLLOWUP_ROOT.mkdir(parents=True,exist_ok=True)
RANDOM_SEEDS=(0,1,2,3);SEED=20260913;PATCH_CONDITION_BATCH_SIZE=1
BOOTSTRAP_REPLICATES=10000;NORM_RELATIVE_TOLERANCE=.02
LABELS=('A','B','C');DONOR_TASKS=('weight_more','weight_less');TARGET_TASKS=('outcome',)
DIAGNOSTIC_VARIANTS=('forward','reverse');SITE_SCOPE='final_prompt_token'
def stable_key(value):return hashlib.sha256(f'{SEED}:{value!r}'.encode()).hexdigest()
def outcome(value):return 'left' if value>0 else 'right' if value<0 else 'balanced'
sha256_file=lambda p:'sha256:'+file_hash(p)
write_json_atomic=save_json

EXPECTED_FAMILIES=64  # Lock before viewing any new outputs; divisible by four.
assert EXPECTED_FAMILIES>=32 and EXPECTED_FAMILIES%4==0
SCAN_LAYERS=tuple(SPEC['scan_layers']);CAPTURE_LAYERS=SCAN_LAYERS;ENDPOINT_LAYER=SPEC['endpoint_layer']
NORMALIZED_DEPTHS=tuple((x+1)/EXPECTED_LAYER_COUNT for x in SCAN_LAYERS)
RECORDS_PER_LAYER_FAMILY=12;RECORDS_PER_FAMILY=12*len(SCAN_LAYERS);EXPECTED_RECORDS=EXPECTED_FAMILIES*RECORDS_PER_FAMILY
MIN_FAMILIES=32;ALPHA=.05;SMOKE_CENTERED_LOGPROB_TOLERANCE=.15
SHARED_ROOT=FOLLOWUP_ROOT/'fixed_content'/RUN_ID
OUTPUT_ROOT=SHARED_ROOT/'models'/MODEL_SLUG;SHARD_DIR=OUTPUT_ROOT/'depth_shards'
ANALYSIS_DIR=OUTPUT_ROOT/'analysis';CROSS_MODEL_DIR=SHARED_ROOT/'cross_model_analysis'
for p in (SHARED_ROOT,OUTPUT_ROOT,SHARD_DIR,ANALYSIS_DIR,CROSS_MODEL_DIR):p.mkdir(parents=True,exist_ok=True)
canonical_protocol_identity=dict(schema='fixed-content-1.0',models=MODEL_SPECS,n=EXPECTED_FAMILIES,seed=SEED,
    implementation=IMPLEMENTATION_SHA256,scope=SITE_SCOPE,dtype=MODEL_DTYPE,batch_size=1,
    diagnostic_variants=DIAGNOSTIC_VARIANTS,donor_tasks=DONOR_TASKS,global_primary_tests=37,
    gate='lower95 > 0.1 and BH q < 0.05; carrier + effect + dominance',
    random_matching='same actual native-dtype displacement at each recipient, tolerance 2%',
    interpretation='fixed sites only; not a full continuous transition')
canonical_protocol_identity=json.loads(json.dumps(canonical_protocol_identity))
freeze(SHARED_ROOT/'protocol.json',canonical_protocol_identity)
print('Model/layers/families:',MODEL_KEY,SCAN_LAYERS,EXPECTED_FAMILIES)

Freeze fixed-site protocol:  33%|###3      | 5/15 [00:00<?, ?cell/s]

Model/layers/families: qwen9b (31,) 64

In [8]:
%%cell_progress 7/15 Generate and freeze new physical support before loading any model
from visual_torque_toolkit.render import RenderStyle, render_scene
from visual_torque_toolkit.world import Scene, Side, Stack
import shutil
excluded,exclusion_identity=exclusion_snapshot(PROJECT_ROOT,FOLLOWUP_ROOT,DATASET_DIR)
support_dir=FOLLOWUP_ROOT/'support'/('fixed_content_'+RUN_ID)
support_dir.mkdir(parents=True,exist_ok=True)
support_file=support_dir/'support.json'
support_config=dict(n=EXPECTED_FAMILIES,seed=SEED,generator='inverse_equal_net_mirror_disjoint_1',
                    exclusions=digest(exclusion_identity))
freeze(support_dir/'protocol.json',support_config)
if support_file.is_file():
    support_payload=read_json(support_file)
    assert support_payload['config']==support_config
    depth_support=support_payload['families']
else:
    # Explicitly avoid any repair-confirmation support already created in this bundle.
    for path in (FOLLOWUP_ROOT/'support').glob('repair_*/support.json'):
        excluded.update(geometries_in(read_json(path)))
    depth_support=inverse_families(EXPECTED_FAMILIES,SEED,excluded)
    save_json(support_file,dict(config=support_config,families=depth_support))
assert len(depth_support)==EXPECTED_FAMILIES
all_signatures=[geometry_signature(role['stacks']) for r in depth_support for role in r['roles'].values()]
assert len(set(all_signatures))==2*EXPECTED_FAMILIES
assert not set(all_signatures)&excluded
PRIOR_SCENE_DIR=support_dir/'images';PRIOR_SCENE_DIR.mkdir(exist_ok=True)
image_filenames=[]
for row in tqdm(depth_support,desc='Rendering fixed confirmation families'):
    a,b=row['roles']['base'],row['roles']['aligned_source']
    assert a['features']['net_torque']==b['features']['net_torque']
    assert [(x['side'],x['distance']) for x in a['stacks']]==[(x['side'],x['distance']) for x in b['stacks']]
    assert a['features']['weight_score']*b['features']['weight_score']<0
    for role in row['roles'].values():
        path=PRIOR_SCENE_DIR/role['image_filename'];image_filenames.append(role['image_filename'])
        if not path.is_file():
            scene=Scene(role['scene_id'],tuple(Stack(str(i),Side(s['side']),int(s['distance']),int(s['units'])) for i,s in enumerate(role['stacks'])))
            render_scene(scene,path,RenderStyle(ticks_per_side=6))
RUNTIME_SCENE_DIR=Path('/content/visualtorque_fixed_confirmation')/RUN_ID
RUNTIME_SCENE_DIR.mkdir(parents=True,exist_ok=True)
for name in image_filenames:
    src,dst=PRIOR_SCENE_DIR/name,RUNTIME_SCENE_DIR/name
    if not dst.is_file() or file_hash(dst)!=file_hash(src):shutil.copy2(src,dst)
support_identity=dict(schema_version='new-fixed-content-support-1.0',support_sha256=file_hash(support_file),
    family_ids=[r['family_id'] for r in depth_support],geometry_disjoint=True,mirror_canonical=True,
    prior_manifest_sha256=digest(exclusion_identity),analysis_status='new_fixed_site_confirmation')
remap_manifest_sha256=file_hash(support_file)
print('New families:',len(depth_support),'| selected without model outputs')

Generate and freeze new physical support before loading any model:  40%|####      | 6/15 [00:00<?, ?cell/s]

Rendering fixed confirmation families:   0%|          | 0/64 [00:00<?, ?it/s]

New families: 64 | selected without model outputs

In [9]:
%%cell_progress 8/15 Load pinned model
cell_stage(f'Loading {MODEL_KEY} weights for depth localization')
import gc
if 'adapter' in globals():
    del adapter
    gc.collect()
    torch.cuda.empty_cache()

adapter = HuggingFaceMultimodalAdapter(
    MODEL_ID, revision=MODEL_REVISION,
    dtype=MODEL_DTYPE, device_map=DEVICE_MAP,
)
display(adapter.metadata)
assert adapter.metadata['resolved_revision'] == MODEL_REVISION

def resolve_module_path(root, path):
    value = root
    for component in path.split('.'):
        value = getattr(value, component)
    return value

def discover_decoder_layers(model):
    candidates = (
        'model.language_model.layers', 'model.text_model.layers',
        'language_model.model.layers', 'model.model.layers',
        'model.layers', 'language_model.layers',
    )
    for path in candidates:
        try:
            layers = resolve_module_path(model, path)
        except AttributeError:
            continue
        if isinstance(layers, torch.nn.ModuleList) and len(layers) >= 8:
            return path, layers
    raise RuntimeError('Could not locate decoder layers.')

LAYER_PATH, DECODER_LAYERS = discover_decoder_layers(adapter.model)
assert len(DECODER_LAYERS) == EXPECTED_LAYER_COUNT
assert all(0 <= layer < len(DECODER_LAYERS) for layer in CAPTURE_LAYERS)
print('Layer path:', LAYER_PATH)
print('Capture layers:', CAPTURE_LAYERS)
assert not any(v == 'disk' for v in getattr(adapter.model,'hf_device_map',{}).values()), 'Use a GPU with enough memory for this model.'

Load pinned model:  47%|####6     | 7/15 [00:00<?, ?cell/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

preprocessor_config.json:   0%|          | 0.00/390 [00:00<?, ?B/s]

chat_template.jinja:   0%|          | 0.00/7.76k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/3.13k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/16.7k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/6.72M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/3.35M [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 12.8MB

tokenizer.json: downloading bytes:           |  0.00B

video_preprocessor_config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/79.7k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

[transformers] The fast path is not available because one of the required library is not installed. Falling back to torch implementation. To install follow https://github.com/fla-org/flash-linear-attention#installation and https://github.com/Dao-AILab/causal-conv1d

Loading weights:   0%|          | 0/760 [00:00<?, ?it/s]

{'adapter': 'HuggingFaceMultimodalAdapter',
 'model_id': 'Qwen/Qwen3.5-9B',
 'requested_revision': 'c202236235…337b9a',
 'resolved_revision': 'c202236235…337b9a',
 'dtype': 'bfloat16',
 'device_map': 'auto',
 'parameter_count': 9409813744,
 'torch_version': '2.11.0+cu128',
 'transformers_version': '5.14.0'}

Layer path: model.language_model.layers
Capture layers: (31,)

In [10]:
%%cell_progress 9/15 Define original remapping prompts
cell_stage('Constructing mappings that separate semantic, label, and position')
import math
from visual_torque_toolkit.behavior import PromptCondition
from visual_torque_toolkit.behavior.data import BehaviorExample

RULE_TEXT = (
    'Each square is one unit of weight. Distance is measured in tick '
    'intervals from the center pivot. Torque equals weight times distance. '
    'Total torque on a side is the sum over stacks on that side.'
)
QUESTION_TEXT = {
    'outcome': 'Which way will the balance scale tip?',
    'weight_more': 'Which side has more total weight?',
    'weight_less': 'Which side has less total weight?',
}
SEMANTIC_TEXT = {
    'left': 'left side', 'balanced': 'equal', 'right': 'right side',
}

def task_semantic(features, task):
    if task == 'outcome':
        value = int(features['net_torque'])
    elif task == 'weight_more':
        value = int(features['weight_score'])
    elif task == 'weight_less':
        value = -int(features['weight_score'])
    else:
        raise KeyError(task)
    return outcome(value)

def reference_mapping(row):
    semantics = ['left', 'balanced', 'right']
    offset = int(stable_key(f"options:{row['family_id']}")[:8], 16) % 3
    semantics = semantics[offset:] + semantics[:offset]
    return tuple({
        'position': index, 'label': LABELS[index], 'semantic': semantics[index]
    } for index in range(3))

def diagnostic_mapping(row, donor_semantic, variant):
    reference = reference_mapping(row)
    donor_position = next(
        item['position'] for item in reference
        if item['semantic'] == donor_semantic
    )
    donor_label = reference[donor_position]['label']
    other_positions = [value for value in range(3) if value != donor_position]
    other_semantics = [
        value for value in ('left', 'balanced', 'right')
        if value != donor_semantic
    ]
    other_labels = [value for value in LABELS if value != donor_label]
    if variant == 'reverse':
        other_semantics.reverse()
        other_labels.reverse()
    elif variant != 'forward':
        raise KeyError(variant)
    label_position, semantic_position = other_positions
    mapping = [None, None, None]
    mapping[donor_position] = {
        'position': donor_position,
        'label': other_labels[0],
        'semantic': other_semantics[0],
    }
    mapping[label_position] = {
        'position': label_position,
        'label': donor_label,
        'semantic': other_semantics[1],
    }
    mapping[semantic_position] = {
        'position': semantic_position,
        'label': other_labels[1],
        'semantic': donor_semantic,
    }
    assert {item['label'] for item in mapping} == set(LABELS)
    assert {item['semantic'] for item in mapping} == {'left', 'balanced', 'right'}
    semantic_candidate = next(
        item['label'] for item in mapping if item['semantic'] == donor_semantic
    )
    label_candidate = donor_label
    position_candidate = mapping[donor_position]['label']
    assert len({semantic_candidate, label_candidate, position_candidate}) == 3
    diagnostics = {
        'donor_semantic': donor_semantic,
        'donor_label': donor_label,
        'donor_position': donor_position,
        'semantic_candidate': semantic_candidate,
        'label_candidate': label_candidate,
        'position_candidate': position_candidate,
    }
    return tuple(mapping), diagnostics

def semantics_by_label(mapping):
    return tuple(
        next(item['semantic'] for item in mapping if item['label'] == label)
        for label in LABELS
    )

def custom_prompt(task, mapping):
    options = '\n'.join(
        f"{item['label']}. {SEMANTIC_TEXT[item['semantic']]}"
        for item in mapping
    )
    return '\n\n'.join([
        'Answer this question using only the supplied balance-scale scene.',
        RULE_TEXT,
        'Question: ' + QUESTION_TEXT[task],
        'Options:\n' + options,
        'Do not explain your reasoning. Reply with exactly one option '
        'letter and nothing else. Valid replies are: A, B, C.',
    ])

def make_example(row, task, role, mapping, name):
    role_record = row['roles'][role]
    features = role_record['features']
    semantics = semantics_by_label(mapping)
    gold = task_semantic(features, task)
    return BehaviorExample(
        example_id=f"remap:{row['family_id']}:{name}:{role}",
        question_id=f"remap_{row['family_id']}_{name}",
        scene_id=str(role_record['scene_id']),
        condition=PromptCondition.IMAGE_RULE,
        question_kind=task,
        variant='response_state_remapping',
        split=str(row['remapping_split']),
        problem_type='semantic_label_position_separation',
        outcome=gold,
        net_torque=int(features['net_torque']),
        prompt=custom_prompt(task, mapping),
        image_path=(RUNTIME_SCENE_DIR / role_record['image_filename']).resolve(),
        labels=LABELS,
        option_text=tuple(
            SEMANTIC_TEXT[value] for value in semantics
        ),
        option_semantics=semantics,
        gold_label=LABELS[semantics.index(gold)],
        gold_semantic=gold,
    )

def donor_semantic_for(row, donor_task):
    return task_semantic(row['roles']['aligned_source']['features'], donor_task)

def build_reference_examples(row):
    mapping = reference_mapping(row)
    examples = {}
    for donor_task in DONOR_TASKS:
        for role in ('base', 'aligned_source'):
            key = f'ref__{donor_task}__{role}'
            examples[key] = make_example(
                row, donor_task, role, mapping, f'ref_{donor_task}'
            )
    return examples

def build_diagnostic_examples(row):
    examples = {}
    diagnostics = {}
    for donor_task in DONOR_TASKS:
        donor_semantic = donor_semantic_for(row, donor_task)
        for target_task in TARGET_TASKS:
            for variant in DIAGNOSTIC_VARIANTS:
                mapping, info = diagnostic_mapping(
                    row, donor_semantic, variant
                )
                key = f'diag__{donor_task}__{target_task}__{variant}'
                examples[key] = make_example(
                    row, target_task, 'base', mapping, key
                )
                diagnostics[key] = info
    return examples, diagnostics

def output_hidden_tensor(output):
    if torch.is_tensor(output):
        hidden = output
    elif isinstance(output, (tuple, list)) and output and torch.is_tensor(output[0]):
        hidden = output[0]
    elif hasattr(output, 'last_hidden_state') and torch.is_tensor(output.last_hidden_state):
        hidden = output.last_hidden_state
    else:
        raise TypeError(f'Unsupported output: {type(output).__name__}')
    assert hidden.ndim == 3
    return hidden

def replace_output_hidden(output, modified):
    if torch.is_tensor(output):
        return modified
    if isinstance(output, tuple):
        return (modified,) + output[1:]
    if isinstance(output, list):
        return [modified] + output[1:]
    raise TypeError(type(output).__name__)

def prepare_examples(examples):
    examples = tuple(examples)
    plan = adapter._candidate_plan(examples[0])
    if plan is None:
        raise RuntimeError('A/B/C labels must be single-token candidates.')
    for example in examples[1:]:
        assert adapter._candidate_plan(example) == plan
    fixed_prefix, token_by_label = plan
    inputs = adapter._append_text_prefix(
        adapter._to_device(adapter._template(
            [example.messages() for example in examples],
            add_generation_prompt=True,
        )), fixed_prefix,
    )
    return {'examples': examples, 'inputs': inputs, 'token_by_label': token_by_label}

def final_mask(prepared):
    assert len(prepared['examples']) == 1
    attention = prepared['inputs']['attention_mask'][0].detach().cpu().bool()
    mask = torch.zeros_like(attention)
    mask[int(torch.where(attention)[0][-1])] = True
    return mask

print('Depth-localization mappings ready.')

Define original remapping prompts:  53%|#####3    | 8/15 [00:00<?, ?cell/s]

Depth-localization mappings ready.

In [11]:
%%cell_progress 10/15 Define native matched remapping interventions
cell_stage('Defining variable-layer final-token transport')

def score_records(prepared, logits):
    logprobs = torch.log_softmax(logits[:, -1, :].float(), dim=-1)
    records = []
    for index, example in enumerate(prepared['examples']):
        scores = [
            float(logprobs[index, prepared['token_by_label'][label]].detach().cpu())
            for label in example.labels
        ]
        maximum = max(scores)
        weights = [math.exp(value - maximum) for value in scores]
        probabilities = [value / sum(weights) for value in weights]
        predicted = int(np.argmax(scores))
        records.append({
            'candidate_labels': list(example.labels),
            'candidate_semantics': list(example.option_semantics),
            'candidate_logprobs': scores,
            'candidate_probabilities': probabilities,
            'predicted_label': example.labels[predicted],
            'predicted_semantic': example.option_semantics[predicted],
            'gold_label': example.gold_label,
            'gold_semantic': example.gold_semantic,
        })
    return records

def forward_capture(prepared, layers):
    hidden_by_layer = {}
    handles = []
    for layer in layers:
        def hook(_module, _inputs, output, layer=layer):
            hidden_by_layer[layer] = output_hidden_tensor(
                output
            ).detach().cpu().clone()
        handles.append(DECODER_LAYERS[layer].register_forward_hook(hook))
    try:
        with torch.inference_mode():
            output = adapter.model(**prepared['inputs'], use_cache=False)
    finally:
        for handle in handles:
            handle.remove()
    return score_records(prepared, output.logits), hidden_by_layer

def capture_examples(examples, layers):
    scores = {}
    hidden = {name: {} for name in examples}
    masks = {}
    for name, example in examples.items():
        prepared = prepare_examples([example])
        masks[name] = final_mask(prepared)
        current_scores, current_hidden = forward_capture(prepared, layers)
        scores[name] = current_scores[0]
        for layer, tensor in current_hidden.items():
            hidden[name][layer] = tensor[0]
        del prepared, current_hidden
    return scores, hidden, masks

def selected_norm(tensor):
    return float(torch.linalg.vector_norm(tensor.float()))

def matched_random(tensor, key):
    generator = torch.Generator(device='cpu')
    generator.manual_seed(int(stable_key(key)[:16], 16) % (2**63 - 1))
    noise = torch.randn(tensor.shape, generator=generator, dtype=torch.float32)
    return (noise * (selected_norm(tensor) / selected_norm(noise))).to(tensor.dtype)

def forward_intervention_chunk(prepared, conditions):
    assert len(prepared['examples']) == len(conditions)
    layers = {int(row['layer_index']) for row in conditions}
    assert len(layers) == 1
    layer = next(iter(layers))
    payloads = torch.stack([row['payload_selected'] for row in conditions])
    masks = torch.stack([row['target_mask'] for row in conditions])
    modes = [row['intervention_mode'] for row in conditions]
    counts = []
    displacement_audits = []
    def hook(_module, _inputs, output):
        hidden = output_hidden_tensor(output)
        payload = payloads.to(device=hidden.device, dtype=hidden.dtype)
        mask = masks.to(device=hidden.device)
        modified = hidden.clone()
        displacement_audits.clear()
        counts.clear()
        for index, mode in enumerate(modes):
            current = mask[index]
            assert int(current.sum()) == int(payload[index].shape[0]) == 1
            if mode == 'add':
                modified[index, current] = hidden[index, current] + payload[index]
            elif mode == 'replace':
                modified[index, current] = payload[index]
            else:
                raise ValueError(mode)
            if str(conditions[index].get('condition','')).endswith('_random'):
                reference=conditions[index]['reference_payload_selected'].to(device=hidden.device,dtype=hidden.dtype)
                pre_native=hidden[index,current]
                target_norm=float(((pre_native+reference).float()-pre_native.float()).norm())
                cast=lambda x:torch.as_tensor(np.asarray(x).copy(),dtype=hidden.dtype).float().numpy()
                raw_direction=payload[index].float().cpu().numpy()
                if np.linalg.norm(raw_direction)==0:raw_direction=np.ones_like(raw_direction)
                post,audit=native_norm_edit(pre_native.float().cpu().numpy(),raw_direction,target_norm,cast)
                modified[index,current]=torch.as_tensor(post,device=hidden.device,dtype=hidden.dtype)
                conditions[index]['native_norm_matched']=audit['matched']
                conditions[index]['native_norm_relative_error']=audit['relative_error']
                conditions[index]['reference_actual_delta_norm']=target_norm
            counts.append(int(current.sum()))
            pre = hidden[index, current].float()
            realized = modified[index, current].float() - pre
            requested = (payload[index].float() if mode == 'add' else payload[index].float() - pre)
            displacement_audits.append({
                'actual_delta_norm': float(realized.norm()),
                'requested_delta_norm': float(requested.norm()),
                'cast_error_norm': float((realized - requested).norm()),
            })

        return replace_output_hidden(output, modified)
    handle = DECODER_LAYERS[layer].register_forward_hook(hook)
    try:
        with torch.inference_mode():
            output = adapter.model(**prepared['inputs'], use_cache=False)
    finally:
        handle.remove()
    records = score_records(prepared, output.logits)
    for record, condition, count in zip(records, conditions, counts):
        record.update({
            key: value for key, value in condition.items()
            if key not in ('payload_selected', 'target_mask', 'reference_payload_selected')
        })
        record['patched_tokens'] = count
    for record, audit_row in zip(records, displacement_audits):
        record.update(audit_row)
    return records


def score_conditions(example, conditions):
    records = []
    grouped = defaultdict(list)
    for condition in conditions:
        grouped[int(condition['layer_index'])].append(condition)
    for layer_conditions in grouped.values():
        for start in range(0, len(layer_conditions), PATCH_CONDITION_BATCH_SIZE):
            actual = layer_conditions[start:start + PATCH_CONDITION_BATCH_SIZE]
            padded = list(actual)
            while len(padded) < PATCH_CONDITION_BATCH_SIZE:
                padded.append(padded[-1])
            prepared = prepare_examples([example] * len(padded))
            records.extend(forward_intervention_chunk(
                prepared, padded
            )[:len(actual)])
            del prepared
    return records

def centered_scores(record):
    values = np.asarray(record['candidate_logprobs'], dtype=float)
    return values - values.mean()

def label_score(record, label):
    labels = list(record['candidate_labels'])
    values = np.asarray(record['candidate_logprobs'], dtype=float)
    index = labels.index(label)
    other = np.delete(values, index)
    return float(values[index] - np.logaddexp.reduce(other))

def entropy(record):
    probabilities = np.asarray(record['candidate_probabilities'], dtype=float)
    return float(-np.sum(probabilities * np.log(np.clip(probabilities, 1e-12, 1))))

print('Multi-layer final-token scorers ready.')

Define native matched remapping interventions:  60%|######    | 9/15 [00:00<?, ?cell/s]

Multi-layer final-token scorers ready.

In [12]:
%%cell_progress 11/15 Verify one unchanged critical path
cell_stage('Checking all fixed depths and three mutually exclusive candidates')
smoke_row = depth_support[0]
reference_examples = build_reference_examples(smoke_row)
diagnostic_examples, diagnostic_info = build_diagnostic_examples(smoke_row)
for key, info in diagnostic_info.items():
    assert len({
        info['semantic_candidate'], info['label_candidate'],
        info['position_candidate'],
    }) == 3, key

smoke_examples = {**reference_examples, **diagnostic_examples}
smoke_scores, smoke_hidden, smoke_masks = capture_examples(
    smoke_examples, SCAN_LAYERS
)
token_ids = []
for name, example in smoke_examples.items():
    prepared = prepare_examples([example])
    ids = prepared['inputs']['input_ids'][0].detach().cpu()
    token_ids.append(ids[final_mask(prepared)].tolist())
assert all(value == token_ids[0] for value in token_ids)

target_key = 'diag__weight_more__outcome__forward'
smoke_errors = {}
for layer in SCAN_LAYERS:
    self_record = score_conditions(smoke_examples[target_key], [{
        'family_id': smoke_row['family_id'], 'condition': 'self_replay',
        'layer_index': layer, 'intervention_mode': 'replace',
        'payload_selected': smoke_hidden[target_key][layer][smoke_masks[target_key]],
        'target_mask': smoke_masks[target_key],
    }])[0]
    error = float(np.max(np.abs(
        centered_scores(self_record) - centered_scores(smoke_scores[target_key])
    )))
    assert error < SMOKE_CENTERED_LOGPROB_TOLERANCE, (layer, error)
    assert self_record['patched_tokens'] == 1
    smoke_errors[layer] = error
print('Three diagnostic candidates:', diagnostic_info[target_key])
print('Final token ID:', token_ids[0])
print('Self parity by layer:', smoke_errors)
del smoke_hidden
torch.cuda.empty_cache()

Verify one unchanged critical path:  67%|######6   | 10/15 [00:00<?, ?cell/s]

Three diagnostic candidates: {'donor_semantic': 'right', 'donor_label': 'B', 'donor_position': 1, 'semantic_candidate': 'C', 'label_candidate': 'B', 'position_candidate': 'A'}
Final token ID: [271]
Self parity by layer: {31: 0.0}

In [13]:
%%cell_progress 12/15 Capture or resume new families
cell_stage('Applying donor and equal-norm random directions at every depth')


# Include code, environment, exact pixels and prompt construction in resumption identity.
import inspect
import platform
import transformers
def fingerprint_sources():
    files = sorted((TOOLKIT_ROOT / 'src' / 'visual_torque_toolkit').rglob('*.py'))
    return {str(p.relative_to(TOOLKIT_ROOT)): sha256_file(p) for p in files}

image_hashes = {name: sha256_file(PRIOR_SCENE_DIR / name)
                for name in sorted(set(image_filenames))}
for name, expected_hash in image_hashes.items():
    assert sha256_file(RUNTIME_SCENE_DIR / name) == expected_hash
runtime_identity = {
    'implementation_sha256': IMPLEMENTATION_SHA256,
    'torch': torch.__version__, 'transformers': transformers.__version__,
    'dtype': MODEL_DTYPE,
    'capture_batch_size': globals().get('CAPTURE_BATCH_SIZE', 1),
    'patch_batch_size': PATCH_CONDITION_BATCH_SIZE,
    'toolkit_files': fingerprint_sources(), 'image_hashes': image_hashes,
}

capture_identity = {
    'runtime_identity': runtime_identity,
    'schema_version': 'semantic-label-depth-capture-1.0',
    'protocol_identity': canonical_protocol_identity,
    'support_identity': support_identity,
    'model_id': MODEL_ID,
    'resolved_revision': adapter.metadata['resolved_revision'],
    'scan_layers': list(SCAN_LAYERS),
    'normalized_depths': list(NORMALIZED_DEPTHS),
    'scope': SITE_SCOPE,
    'records_per_family': RECORDS_PER_FAMILY,
}
CAPTURE_SHA256 = 'sha256:' + hashlib.sha256(
    json.dumps(capture_identity, sort_keys=True).encode('utf-8')
).hexdigest()
config_path = OUTPUT_ROOT / 'capture_config.json'
if config_path.is_file():
    previous = json.loads(config_path.read_text(encoding='utf-8'))
    assert previous.get('identity') == capture_identity
else:
    write_json_atomic(config_path, {
        'identity': capture_identity,
        'capture_identity_sha256': CAPTURE_SHA256,
        'created_at_utc': datetime.now(timezone.utc).isoformat(),
    })

completed_ids = set()
for path in sorted(SHARD_DIR.glob('*.json')):
    payload = json.loads(path.read_text(encoding='utf-8'))
    assert payload['capture_identity_sha256'] == CAPTURE_SHA256
    assert len(payload['patch_records']) == RECORDS_PER_FAMILY
    assert payload['family_id'] not in completed_ids, 'Duplicate family shard'
    completed_ids.add(payload['family_id'])
assert completed_ids <= {str(r['family_id']) for r in depth_support}
print('Completed / total:', len(completed_ids), len(depth_support))

remaining_families = sum(
    str(row['family_id']) not in completed_ids for row in depth_support
)
layer_progress = tqdm(
    total=remaining_families * len(SCAN_LAYERS),
    desc=f'{MODEL_KEY} intervention layers', unit='layer-family',
)
for row in tqdm(depth_support, desc=f'{MODEL_KEY} depth scan', unit='family'):
    family_id = str(row['family_id'])
    if family_id in completed_ids:
        continue
    reference_examples = build_reference_examples(row)
    diagnostic_examples, diagnostic_info = build_diagnostic_examples(row)
    all_examples = {**reference_examples, **diagnostic_examples}
    scores, hidden, masks = capture_examples(all_examples, SCAN_LAYERS)
    donor_deltas = {layer: {} for layer in SCAN_LAYERS}
    random_deltas = {layer: {} for layer in SCAN_LAYERS}
    donor_norms = {str(layer): {} for layer in SCAN_LAYERS}
    for layer in SCAN_LAYERS:
        for donor_task in DONOR_TASKS:
            base_key = f'ref__{donor_task}__base'
            source_key = f'ref__{donor_task}__aligned_source'
            delta = (
                hidden[source_key][layer][masks[source_key]]
                - hidden[base_key][layer][masks[base_key]]
            )
            donor_deltas[layer][donor_task] = delta
            donor_norms[str(layer)][donor_task] = selected_norm(delta)
            random_deltas[layer][donor_task] = matched_random(
                delta, f'depth:{family_id}:{layer}:{donor_task}'
            )

    patch_records = []
    for layer in SCAN_LAYERS:
        normalized_depth = (layer + 1) / EXPECTED_LAYER_COUNT
        for donor_task in DONOR_TASKS:
            reference_key = f'ref__{donor_task}__base'
            donor_norm = donor_norms[str(layer)][donor_task]
            identity_conditions = []
            for condition, payload in (
                ('identity_donor', donor_deltas[layer][donor_task]),
                ('identity_random', random_deltas[layer][donor_task]),
            ):
                identity_conditions.append({
                    'family_id': family_id, 'mapping_type': 'identity',
                    'variant': 'reference', 'donor_task': donor_task,
                    'target_task': donor_task, 'condition': condition,
                    'layer_index': layer,
                    'normalized_depth': normalized_depth,
                    'intervention_mode': 'add',
                    'payload_selected': payload,
                    'reference_payload_selected': donor_deltas[layer][donor_task],
                    'target_mask': masks[reference_key],
                    'donor_norm': donor_norm,
                    'applied_norm': selected_norm(payload),
                })
            patch_records.extend(score_conditions(
                reference_examples[reference_key], identity_conditions
            ))
            for variant in DIAGNOSTIC_VARIANTS:
                key = f'diag__{donor_task}__outcome__{variant}'
                conditions = []
                for condition, payload in (
                    ('diagnostic_donor', donor_deltas[layer][donor_task]),
                    ('diagnostic_random', random_deltas[layer][donor_task]),
                ):
                    conditions.append({
                        'family_id': family_id,
                        'mapping_type': 'diagnostic', 'variant': variant,
                        'donor_task': donor_task, 'target_task': 'outcome',
                        'condition': condition, 'layer_index': layer,
                        'normalized_depth': normalized_depth,
                        'intervention_mode': 'add',
                        'payload_selected': payload,
                    'reference_payload_selected': donor_deltas[layer][donor_task],
                        'target_mask': masks[key],
                        'donor_norm': donor_norm,
                        'applied_norm': selected_norm(payload),
                    })
                current = score_conditions(diagnostic_examples[key], conditions)
                for record in current:
                    record['diagnostics'] = diagnostic_info[key]
                    record['target_key'] = key
                patch_records.extend(current)
        layer_progress.update(1)
    assert len(patch_records) == RECORDS_PER_FAMILY
    write_json_atomic(SHARD_DIR / f'{family_id}.json', {
        'schema_version': 'semantic-label-depth-shard-1.0',
        'capture_identity_sha256': CAPTURE_SHA256,
        'family_id': family_id,
        'baseline_scores': scores,
        'diagnostic_info': diagnostic_info,
        'donor_norms': donor_norms,
        'patch_records': patch_records,
    })
    del hidden
    torch.cuda.empty_cache()
layer_progress.close()

shards = sorted(SHARD_DIR.glob('*.json'))
assert len(shards) == EXPECTED_FAMILIES
print('Depth capture complete:', len(shards), 'families')

Capture or resume new families:  73%|#######3  | 11/15 [00:00<?, ?cell/s]

Completed / total: 0 64

qwen9b intervention layers:   0%|          | 0/64 [00:00<?, ?layer-family/s]

qwen9b depth scan:   0%|          | 0/64 [00:00<?, ?family/s]

Depth capture complete: 64 families

In [14]:
%%cell_progress 13/15 Assemble original family estimands
cell_stage('Converting every layer intervention into family-level effects')
import gc
del adapter
gc.collect()
torch.cuda.empty_cache()

def semantic_score(record, semantic):
    semantics = list(record['candidate_semantics'])
    label = record['candidate_labels'][semantics.index(semantic)]
    return label_score(record, label)

def find_record(records, layer, donor_task, target_task, variant, condition):
    matches = [
        record for record in records
        if int(record['layer_index']) == int(layer)
        and record['donor_task'] == donor_task
        and record['target_task'] == target_task
        and record['variant'] == variant
        and record['condition'] == condition
    ]
    assert len(matches) == 1, (
        layer, donor_task, target_task, variant, condition, len(matches)
    )
    return matches[0]

estimand_rows = []
identity_rows = []
behavior_rows = []
for shard_path in tqdm(sorted(SHARD_DIR.glob('*.json')), desc='Estimands', unit='family'):
    payload = json.loads(shard_path.read_text(encoding='utf-8'))
    family_id = payload['family_id']
    records = payload['patch_records']
    row = next(item for item in depth_support if item['family_id'] == family_id)
    for layer in SCAN_LAYERS:
        normalized_depth = (layer + 1) / EXPECTED_LAYER_COUNT
        for donor_task in DONOR_TASKS:
            base_key = f'ref__{donor_task}__base'
            base = payload['baseline_scores'][base_key]
            base_semantic = task_semantic(
                row['roles']['base']['features'], donor_task
            )
            source_semantic = donor_semantic_for(row, donor_task)
            base_margin = (
                semantic_score(base, source_semantic)
                - semantic_score(base, base_semantic)
            )
            donor_record = find_record(
                records, layer, donor_task, donor_task,
                'reference', 'identity_donor'
            )
            random_record = find_record(
                records, layer, donor_task, donor_task,
                'reference', 'identity_random'
            )
            identity_rows.append({
                'family_id': family_id, 'layer_index': layer,
                'normalized_depth': normalized_depth,
                'donor_task': donor_task,
                'effect': float(
                    (semantic_score(donor_record, source_semantic)
                     - semantic_score(donor_record, base_semantic) - base_margin)
                    - (semantic_score(random_record, source_semantic)
                       - semantic_score(random_record, base_semantic) - base_margin)
                ),
            })
            for variant in DIAGNOSTIC_VARIANTS:
                key = f'diag__{donor_task}__outcome__{variant}'
                baseline = payload['baseline_scores'][key]
                info = payload['diagnostic_info'][key]
                donor = find_record(
                    records, layer, donor_task, 'outcome',
                    variant, 'diagnostic_donor'
                )
                random = find_record(
                    records, layer, donor_task, 'outcome',
                    variant, 'diagnostic_random'
                )
                effects = {}
                for state_class, candidate_key in (
                    ('semantic', 'semantic_candidate'),
                    ('label', 'label_candidate'),
                    ('position', 'position_candidate'),
                ):
                    label = info[candidate_key]
                    effects[state_class] = float(
                        (label_score(donor, label) - label_score(baseline, label))
                        - (label_score(random, label) - label_score(baseline, label))
                    )
                estimand_rows.append({
                    'family_id': family_id, 'layer_index': layer,
                    'normalized_depth': normalized_depth,
                    'donor_task': donor_task, 'target_task': 'outcome',
                    'variant': variant,
                    'semantic_effect': effects['semantic'],
                    'label_effect': effects['label'],
                    'position_effect': effects['position'],
                    **info,
                })
                if layer == ENDPOINT_LAYER:
                    behavior_rows.append({
                        'family_id': family_id, 'donor_task': donor_task,
                        'variant': variant,
                        'correct': (
                            baseline['predicted_semantic']
                            == baseline['gold_semantic']
                        ),
                    })

estimand_frame = pd.DataFrame(estimand_rows)
identity_frame = pd.DataFrame(identity_rows)
behavior_frame = pd.DataFrame(behavior_rows)
assert len(estimand_frame) == (
    EXPECTED_FAMILIES * len(SCAN_LAYERS)
    * len(DONOR_TASKS) * len(DIAGNOSTIC_VARIANTS)
)
assert len(identity_frame) == (
    EXPECTED_FAMILIES * len(SCAN_LAYERS) * len(DONOR_TASKS)
)

family_rows = []
for (family_id, layer), frame in estimand_frame.groupby([
    'family_id', 'layer_index'
]):
    semantic = float(frame['semantic_effect'].mean())
    label = float(frame['label_effect'].mean())
    position = float(frame['position_effect'].mean())
    identity = float(identity_frame[
        (identity_frame['family_id'] == family_id)
        & (identity_frame['layer_index'] == layer)
    ]['effect'].mean())
    family_rows.append({
        'family_id': family_id, 'layer_index': int(layer),
        'normalized_depth': (int(layer) + 1) / EXPECTED_LAYER_COUNT,
        'identity_carrier': identity,
        'semantic_effect': semantic,
        'label_effect': label,
        'position_effect': position,
        'semantic_dominance': semantic - max(label, position),
        'label_dominance': label - max(semantic, position),
        'position_dominance': position - max(semantic, label),
        'label_minus_semantic': label - semantic,
    })
family_frame = pd.DataFrame(family_rows)
estimand_frame.to_csv(ANALYSIS_DIR / 'depth_estimands.csv', index=False)
family_frame.to_csv(ANALYSIS_DIR / 'family_depth_metrics.csv', index=False)
behavior_frame.to_csv(ANALYSIS_DIR / 'endpoint_behavior.csv', index=False)
print('Estimands / family-depth rows:', len(estimand_frame), len(family_frame))

Assemble original family estimands:  80%|########  | 12/15 [00:00<?, ?cell/s]

Estimands:   0%|          | 0/64 [00:00<?, ?family/s]

Estimands / family-depth rows: 256 64

In [15]:
%%cell_progress 14/15 Export per-model results without prematurely changing the 37-test family
family_frame['model_key']=MODEL_KEY
family_frame.to_csv(ANALYSIS_DIR/'family_depth_metrics.csv',index=False)
native=[]
for path in sorted(SHARD_DIR.glob('*.json')):
    obj=read_json(path)
    for r in obj['patch_records']:
        native.append({k:v for k,v in r.items() if k not in ('candidate_logprobs','candidate_probabilities','diagnostics')})
pd.DataFrame(native).to_csv(ANALYSIS_DIR/'native_displacement_audit.csv',index=False)
random_writes=[r for r in native if str(r['condition']).endswith('_random')]
assert random_writes and all('native_norm_matched' in r for r in random_writes)
all_controls_valid=all(r['native_norm_matched'] for r in random_writes)
pd.DataFrame([r for r in random_writes if not r['native_norm_matched']]).to_csv(ANALYSIS_DIR/'norm_match_failures.csv',index=False)
save_json(ANALYSIS_DIR/'completion.json',dict(model_key=MODEL_KEY,protocol=digest(canonical_protocol_identity),
    support=support_identity,implementation=IMPLEMENTATION_SHA256,smoke_errors=smoke_errors,
    family_table_sha256=file_hash(ANALYSIS_DIR/'family_depth_metrics.csv'),
    all_native_controls_valid=all_controls_valid,status='model_capture_complete_global_tests_pending'))
display(family_frame.groupby('layer_index')[['identity_carrier','semantic_effect','label_effect','position_effect']].mean())

Export per-model results without prematurely changing the 37-test family:  87%|########6 | 13/15 [00:00<?, ?ce…

             identity_carrier  semantic_effect  label_effect  position_effect
layer_index
31                   1.331589        -0.276459      0.523801        -0.272419

In [16]:
%%cell_progress 15/15 Global 37-test confirmation and fixed-endpoint pairwise comparisons
PRIMARY_METRICS=('identity_carrier','semantic_effect','label_effect','position_effect',
                 'semantic_dominance','label_dominance','position_dominance')
all_frames={};coverage=[];valid_by_model={}
for key,spec in MODEL_SPECS.items():
    folder=SHARED_ROOT/'models'/spec['model_slug']/'analysis'
    complete=folder/'completion.json';table=folder/'family_depth_metrics.csv'
    if not complete.is_file() or not table.is_file():
        coverage.append(dict(model=key,status='not_run'));continue
    marker=read_json(complete)
    assert marker['protocol']==digest(canonical_protocol_identity)
    assert marker['support']==support_identity and marker['implementation']==IMPLEMENTATION_SHA256
    assert marker['family_table_sha256']==file_hash(table)
    data=pd.read_csv(table)
    assert set(data.layer_index)==set(spec['scan_layers']) and not data.duplicated(['family_id','layer_index']).any()
    for layer,sub in data.groupby('layer_index'):assert set(sub.family_id)==set(support_identity['family_ids'])
    all_frames[key]=data;valid_by_model[key]=bool(marker['all_native_controls_valid'])
    coverage.append(dict(model=key,status='complete',all_native_controls_valid=valid_by_model[key]))
display(pd.DataFrame(coverage));pd.DataFrame(coverage).to_csv(CROSS_MODEL_DIR/'coverage.csv',index=False)
tests=[]
for key,data in all_frames.items():
    for layer,sub in data.groupby('layer_index'):
        for metric in PRIMARY_METRICS:
            tests.append(dict(model=key,layer=int(layer),metric=metric,**bootstrap(sub[metric].to_numpy(float),[key,layer,metric])))
    if len(MODEL_SPECS[key]['scan_layers'])==2:
        earlier,later=MODEL_SPECS[key]['scan_layers']
        pivot=data.assign(relative=data.label_effect-data.semantic_effect).pivot(index='family_id',columns='layer_index',values='relative')
        tests.append(dict(model=key,layer=-1,metric='later_minus_earlier_label_relative_to_semantic',
                          **bootstrap((pivot[later]-pivot[earlier]).to_numpy(float),[key,'two_site_difference'])))
test_frame=pd.DataFrame(tests);test_frame['q_value']=np.nan
complete=len(all_frames)==3
decisions=[]
if complete:
    assert len(test_frame)==37
    test_frame['q_value']=bh(test_frame.p_value)
    for key,spec in MODEL_SPECS.items():
        for layer in spec['scan_layers']:
            sub=test_frame[(test_frame.model==key)&(test_frame.layer==layer)].set_index('metric')
            passes=lambda metric:bool(sub.loc[metric,'lower']>.1 and sub.loc[metric,'q_value']<.05)
            classes=[c for c in ('semantic','label','position') if passes('identity_carrier') and passes(c+'_effect') and passes(c+'_dominance')]
            classification=('technical_control_mismatch' if not valid_by_model[key] else classes[0] if len(classes)==1 else 'unresolved')
            decisions.append(dict(model=key,layer=layer,classification=classification,
                scope='fixed_site_only_not_a_continuous_transition'))
    pairwise=[]
    for left,right in combinations(MODEL_SPECS,2):
        a=all_frames[left][all_frames[left].layer_index.eq(MODEL_SPECS[left]['endpoint_layer'])]
        b=all_frames[right][all_frames[right].layer_index.eq(MODEL_SPECS[right]['endpoint_layer'])]
        result=bootstrap(paired(a,b,'family_id','label_effect'),[left,right,'endpoint'])
        result['p_value']=min(1.,2*min(result['p_value'],1-result['p_value']+1/10001))
        pairwise.append(dict(left_model=left,right_model=right,**result))
    p=pd.DataFrame(pairwise);p['q_value']=bh(p.p_value);p.to_csv(CROSS_MODEL_DIR/'endpoint_pairwise_secondary.csv',index=False)
test_frame.to_csv(CROSS_MODEL_DIR/'fixed_37_tests.csv',index=False)
pd.DataFrame(decisions).to_csv(CROSS_MODEL_DIR/'fixed_site_classification.csv',index=False)
display(test_frame.round(4));display(pd.DataFrame(decisions))
save_json(CROSS_MODEL_DIR/'status.json',dict(complete=complete,expected_tests=37,available_tests=len(tests),
    classification=decisions,interpretation='Two fixed sites can show a content difference; this does not establish a continuous conversion chain.'))
lines=['# 固定位置的新家族确认','',f'已完成模型：{", ".join(all_frames)}。',
       '全部三模型完成后才统一校正预定的 37 个主指标；未完成时不提前给出阶段判定。',
       '单项效应、完整类别判据、两个位置的配对差异分别展示。',
       '样本是新家族；层位来自此前探索。两个位置不能代表完整连续转换轨迹。']
(CROSS_MODEL_DIR/'REPORT_ZH.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print('Results:',CROSS_MODEL_DIR)

Global 37-test confirmation and fixed-endpoint pairwise comparisons:  93%|#########3| 14/15 [00:00<?, ?cell/s]

      model    status all_native_controls_valid
0    qwen9b  complete                      True
1  gemma12b  complete                      True
2   qwen27b   not_run                       NaN

,model,layer,metric,n,mean,lower,upper,p_value,q_value
0,qwen9b,31,identity_carrier,64,1.3316,0.9181,1.7610,0.0001,NaN
1,qwen9b,31,semantic_effect,64,-0.2765,-0.3728,-0.1820,1.0000,NaN
2,qwen9b,31,label_effect,64,0.5238,0.3489,0.6958,0.0001,NaN
3,qwen9b,31,position_effect,64,-0.2724,-0.3597,-0.1912,1.0000,NaN
4,qwen9b,31,semantic_dominance,64,-0.9004,-1.1489,-0.6698,1.0000,NaN
5,qwen9b,31,label_dominance,64,0.7533,0.4925,1.0219,0.0001,NaN
6,qwen9b,31,position_dominance,64,-0.9114,-1.1433,-0.6876,1.0000,NaN
7,gemma12b,37,identity_carrier,64,1.5821,0.0463,3.1400,0.0218,NaN
8,gemma12b,37,semantic_effect,64,1.6982,1.2897,2.1241,0.0001,NaN
9,gemma12b,37,label_effect,64,-0.8106,-1.4739,-0.1281,0.9910,NaN
10,gemma12b,37,position_effect,64,-1.1254,-1.5585,-0.6849,1.0000,NaN
11,gemma12b,37,semantic_dominance,64,0.9456,0.3656,1.4959,0.0006,NaN
12,gemma12b,37,label_dominance,64,-2.5088,-3.5676,-1.5043,1.0000,NaN
13,gemma12b,37,position_dominance,64,-3.4559,-3.8586,-3.0986,1.0000,NaN
14,gemma12b,47,identity_carrier,64,3.6296,1.4557,5.9109,0.0002,NaN
15,gemma12b,47,semantic_effect,64,-0.0194,-0.5090,0.4754,0.5360,NaN
16,gemma12b,47,label_effect,64,2.3142,1.1011,3.6623,0.0001,NaN
17,gemma12b,47,position_effect,64,0.1571,-0.3690,0.7169,0.2983,NaN
18,gemma12b,47,semantic_dominance,64,-3.7051,-5.0861,-2.4768,1.0000,NaN
19,gemma12b,47,label_dominance,64,1.7848,0.1686,3.4646,0.0151,NaN
20,gemma12b,47,position_dominance,64,-3.4432,-4.8433,-2.2020,1.0000,NaN
21,gemma12b,-1,later_minus_earlier_label_relative_to_semantic,64,4.8424,2.9830,6.7508,0.0001,NaN

Empty DataFrame
Columns: []
Index: []

Results: /content/drive/MyDrive/VisualTorque/results/cross_model_followup_v1/fixed_content/main/cross_model_analysis